-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dpu_conv_top_dpu_conv_top_Pipeline_COPY_OC_COPY_H_COPY_W is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem2_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem2_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem2_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem2_0_WREADY : IN STD_LOGIC;
    m_axi_gmem2_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem2_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem2_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem2_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem2_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_RVALID : IN STD_LOGIC;
    m_axi_gmem2_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem2_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem2_0_RLAST : IN STD_LOGIC;
    m_axi_gmem2_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem2_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_BVALID : IN STD_LOGIC;
    m_axi_gmem2_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem2_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    ofmap : IN STD_LOGIC_VECTOR (63 downto 0);
    mul_ln112_1 : IN STD_LOGIC_VECTOR (23 downto 0);
    in_w : IN STD_LOGIC_VECTOR (7 downto 0);
    zext_ln119 : IN STD_LOGIC_VECTOR (7 downto 0);
    mul_ln112 : IN STD_LOGIC_VECTOR (15 downto 0);
    conv_scratch : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of dpu_conv_top_dpu_conv_top_Pipeline_COPY_OC_COPY_H_COPY_W is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv24_1 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal or_ln117_reg_616 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln117_reg_616_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state5_io_grp1 : BOOLEAN;
    signal icmp_ln119_2_reg_620 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_620_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state19_pp0_stage0_iter18_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln115_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem0_blk_n_B : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal gmem0_blk_n_W : STD_LOGIC;
    signal gmem0_blk_n_AW : STD_LOGIC;
    signal gmem2_blk_n_R : STD_LOGIC;
    signal gmem2_blk_n_AR : STD_LOGIC;
    signal first_iter_2_reg_184 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln119_cast_fu_196_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln119_cast_reg_590 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln115_reg_596 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln115_reg_596_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln117_fu_245_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln117_reg_600 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln117_reg_600_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln115_4_fu_266_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln115_4_reg_609 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln115_4_reg_609_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln117_fu_274_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln117_reg_616_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_fu_300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_620_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_620_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_620_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_620_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_620_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_620_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_620_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_620_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_620_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_620_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_620_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_620_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_620_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_620_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_620_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal oh_reg_624 : STD_LOGIC_VECTOR (7 downto 0);
    signal oc_reg_629 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln115_1_fu_347_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln115_1_reg_634 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln117_fu_360_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln117_reg_639 : STD_LOGIC_VECTOR (7 downto 0);
    signal gmem2_addr_reg_644 : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem0_addr_reg_650 : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem2_addr_read_reg_661 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_condition_exit_pp0_iter3_stage0 : STD_LOGIC;
    signal ap_phi_mux_first_iter_2_phi_fu_188_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal add_ln119_3_fu_502_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln117_1_fu_490_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal ow_fu_98 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln119_fu_292_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal oh_1_fu_102 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln117_2_fu_366_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten35_fu_106 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal select_ln117_3_fu_311_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal oc_1_fu_110 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln115_5_fu_353_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten57_fu_114 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal add_ln115_fu_239_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal icmp_ln119_fu_256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_1_fu_261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln115_fu_250_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln119_fu_286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln119_7_fu_280_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln117_1_fu_305_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln115_fu_340_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1_fu_383_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal shl_ln119_1_fu_394_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln119_1_fu_401_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln119_fu_405_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln117_fu_390_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln119_mid1_fu_416_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal select_ln115_1_fu_427_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln117_1_fu_423_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln119_4_fu_445_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln119_1_fu_410_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln119_1_mid1_fu_457_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln115_2_fu_438_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln117_fu_468_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln119_2_fu_464_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln119_5_fu_479_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln115_fu_434_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln119_6_fu_484_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln115_3_fu_450_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln119_3_fu_475_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln119_2_fu_497_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dpu_conv_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component dpu_conv_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter17_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0)) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    first_iter_2_reg_184_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln115_reg_596 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                first_iter_2_reg_184 <= ap_const_lv1_0;
            elsif (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                first_iter_2_reg_184 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    indvar_flatten35_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten35_fu_106 <= ap_const_lv16_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln115_fu_234_p2 = ap_const_lv1_0))) then 
                    indvar_flatten35_fu_106 <= select_ln117_3_fu_311_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten57_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten57_fu_114 <= ap_const_lv24_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln115_fu_234_p2 = ap_const_lv1_0))) then 
                    indvar_flatten57_fu_114 <= add_ln115_fu_239_p2;
                end if;
            end if; 
        end if;
    end process;

    oc_1_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    oc_1_fu_110 <= ap_const_lv8_0;
                elsif (((icmp_ln115_reg_596 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    oc_1_fu_110 <= select_ln115_5_fu_353_p3;
                end if;
            end if; 
        end if;
    end process;

    oh_1_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    oh_1_fu_102 <= ap_const_lv8_0;
                elsif (((icmp_ln115_reg_596 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    oh_1_fu_102 <= select_ln117_2_fu_366_p3;
                end if;
            end if; 
        end if;
    end process;

    ow_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ow_fu_98 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln115_fu_234_p2 = ap_const_lv1_0))) then 
                    ow_fu_98 <= select_ln119_fu_292_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                add_ln115_1_reg_634 <= add_ln115_1_fu_347_p2;
                add_ln117_reg_639 <= add_ln117_fu_360_p2;
                gmem0_addr_reg_650 <= select_ln117_1_fu_490_p3;
                gmem2_addr_read_reg_661 <= m_axi_gmem2_0_RDATA;
                gmem2_addr_reg_644 <= add_ln119_3_fu_502_p2;
                oc_reg_629 <= oc_1_fu_110;
                oh_reg_624 <= oh_1_fu_102;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                icmp_ln115_reg_596_pp0_iter2_reg <= icmp_ln115_reg_596;
                icmp_ln117_reg_600_pp0_iter2_reg <= icmp_ln117_reg_600;
                icmp_ln119_2_reg_620_pp0_iter10_reg <= icmp_ln119_2_reg_620_pp0_iter9_reg;
                icmp_ln119_2_reg_620_pp0_iter11_reg <= icmp_ln119_2_reg_620_pp0_iter10_reg;
                icmp_ln119_2_reg_620_pp0_iter12_reg <= icmp_ln119_2_reg_620_pp0_iter11_reg;
                icmp_ln119_2_reg_620_pp0_iter13_reg <= icmp_ln119_2_reg_620_pp0_iter12_reg;
                icmp_ln119_2_reg_620_pp0_iter14_reg <= icmp_ln119_2_reg_620_pp0_iter13_reg;
                icmp_ln119_2_reg_620_pp0_iter15_reg <= icmp_ln119_2_reg_620_pp0_iter14_reg;
                icmp_ln119_2_reg_620_pp0_iter16_reg <= icmp_ln119_2_reg_620_pp0_iter15_reg;
                icmp_ln119_2_reg_620_pp0_iter17_reg <= icmp_ln119_2_reg_620_pp0_iter16_reg;
                icmp_ln119_2_reg_620_pp0_iter2_reg <= icmp_ln119_2_reg_620;
                icmp_ln119_2_reg_620_pp0_iter3_reg <= icmp_ln119_2_reg_620_pp0_iter2_reg;
                icmp_ln119_2_reg_620_pp0_iter4_reg <= icmp_ln119_2_reg_620_pp0_iter3_reg;
                icmp_ln119_2_reg_620_pp0_iter5_reg <= icmp_ln119_2_reg_620_pp0_iter4_reg;
                icmp_ln119_2_reg_620_pp0_iter6_reg <= icmp_ln119_2_reg_620_pp0_iter5_reg;
                icmp_ln119_2_reg_620_pp0_iter7_reg <= icmp_ln119_2_reg_620_pp0_iter6_reg;
                icmp_ln119_2_reg_620_pp0_iter8_reg <= icmp_ln119_2_reg_620_pp0_iter7_reg;
                icmp_ln119_2_reg_620_pp0_iter9_reg <= icmp_ln119_2_reg_620_pp0_iter8_reg;
                or_ln117_reg_616_pp0_iter2_reg <= or_ln117_reg_616;
                or_ln117_reg_616_pp0_iter3_reg <= or_ln117_reg_616_pp0_iter2_reg;
                select_ln115_4_reg_609_pp0_iter2_reg <= select_ln115_4_reg_609;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln115_reg_596 <= icmp_ln115_fu_234_p2;
                icmp_ln117_reg_600 <= icmp_ln117_fu_245_p2;
                icmp_ln119_2_reg_620 <= icmp_ln119_2_fu_300_p2;
                or_ln117_reg_616 <= or_ln117_fu_274_p2;
                select_ln115_4_reg_609 <= select_ln115_4_fu_266_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    zext_ln119_cast_reg_590(7 downto 0) <= zext_ln119_cast_fu_196_p1(7 downto 0);
            end if;
        end if;
    end process;
    zext_ln119_cast_reg_590(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln115_1_fu_347_p2 <= std_logic_vector(unsigned(oc_1_fu_110) + unsigned(ap_const_lv8_1));
    add_ln115_fu_239_p2 <= std_logic_vector(unsigned(indvar_flatten57_fu_114) + unsigned(ap_const_lv24_1));
    add_ln117_1_fu_305_p2 <= std_logic_vector(unsigned(indvar_flatten35_fu_106) + unsigned(ap_const_lv16_1));
    add_ln117_fu_360_p2 <= std_logic_vector(unsigned(select_ln115_fu_340_p3) + unsigned(ap_const_lv8_1));
    add_ln119_1_fu_410_p2 <= std_logic_vector(unsigned(add_ln119_fu_405_p2) + unsigned(zext_ln117_fu_390_p1));
    add_ln119_2_fu_497_p2 <= std_logic_vector(unsigned(zext_ln119_3_fu_475_p1) + unsigned(conv_scratch));
    add_ln119_3_fu_502_p2 <= std_logic_vector(unsigned(add_ln119_2_fu_497_p2) + unsigned(zext_ln115_fu_434_p1));
    add_ln119_4_fu_445_p2 <= std_logic_vector(unsigned(zext_ln117_1_fu_423_p1) + unsigned(ofmap));
    add_ln119_5_fu_479_p2 <= std_logic_vector(unsigned(zext_ln119_2_fu_464_p1) + unsigned(ofmap));
    add_ln119_6_fu_484_p2 <= std_logic_vector(unsigned(add_ln119_5_fu_479_p2) + unsigned(zext_ln115_fu_434_p1));
    add_ln119_7_fu_280_p2 <= std_logic_vector(unsigned(ow_fu_98) + unsigned(ap_const_lv8_1));
    add_ln119_fu_405_p2 <= std_logic_vector(unsigned(zext_ln119_1_fu_401_p1) + unsigned(ofmap));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter18, m_axi_gmem2_0_RVALID, ap_block_state19_pp0_stage0_iter18_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= (((ap_enable_reg_pp0_iter18 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state19_pp0_stage0_iter18_grp1)) or ((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (m_axi_gmem2_0_RVALID = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter18, m_axi_gmem2_0_RVALID, m_axi_gmem0_0_WREADY, ap_block_state5_io_grp1, ap_block_state19_pp0_stage0_iter18_grp1)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter18 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state19_pp0_stage0_iter18_grp1)) or ((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (m_axi_gmem0_0_WREADY = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (m_axi_gmem2_0_RVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_io_grp1)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter18, m_axi_gmem2_0_RVALID, m_axi_gmem0_0_WREADY, ap_block_state5_io_grp1, ap_block_state19_pp0_stage0_iter18_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((ap_enable_reg_pp0_iter18 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state19_pp0_stage0_iter18_grp1)) or ((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (m_axi_gmem0_0_WREADY = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (m_axi_gmem2_0_RVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_io_grp1)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter18, m_axi_gmem2_0_RVALID, m_axi_gmem0_0_WREADY, ap_block_state5_io_grp1, ap_block_state19_pp0_stage0_iter18_grp1)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter18 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state19_pp0_stage0_iter18_grp1)) or ((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (m_axi_gmem0_0_WREADY = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (m_axi_gmem2_0_RVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_io_grp1)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state19_pp0_stage0_iter18_grp1_assign_proc : process(m_axi_gmem0_0_BVALID, icmp_ln119_2_reg_620_pp0_iter17_reg)
    begin
                ap_block_state19_pp0_stage0_iter18_grp1 <= ((icmp_ln119_2_reg_620_pp0_iter17_reg = ap_const_lv1_1) and (m_axi_gmem0_0_BVALID = ap_const_logic_0));
    end process;


    ap_block_state5_io_grp1_assign_proc : process(m_axi_gmem2_0_ARREADY, m_axi_gmem0_0_AWREADY, or_ln117_reg_616_pp0_iter3_reg)
    begin
                ap_block_state5_io_grp1 <= (((or_ln117_reg_616_pp0_iter3_reg = ap_const_lv1_1) and (m_axi_gmem0_0_AWREADY = ap_const_logic_0)) or ((or_ln117_reg_616_pp0_iter3_reg = ap_const_lv1_1) and (m_axi_gmem2_0_ARREADY = ap_const_logic_0)));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln115_fu_234_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln115_fu_234_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter3_stage0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_subdone, icmp_ln115_reg_596_pp0_iter2_reg)
    begin
        if (((icmp_ln115_reg_596_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter17_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter17_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18)
    begin
        if (((ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_phi_mux_first_iter_2_phi_fu_188_p4_assign_proc : process(ap_enable_reg_pp0_iter2, first_iter_2_reg_184, icmp_ln115_reg_596, ap_block_pp0_stage0)
    begin
        if (((icmp_ln115_reg_596 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_first_iter_2_phi_fu_188_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_first_iter_2_phi_fu_188_p4 <= first_iter_2_reg_184;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    gmem0_blk_n_AW_assign_proc : process(ap_enable_reg_pp0_iter4, m_axi_gmem0_0_AWREADY, or_ln117_reg_616_pp0_iter3_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (or_ln117_reg_616_pp0_iter3_reg = ap_const_lv1_1))) then 
            gmem0_blk_n_AW <= m_axi_gmem0_0_AWREADY;
        else 
            gmem0_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem0_blk_n_B_assign_proc : process(ap_enable_reg_pp0_iter18, m_axi_gmem0_0_BVALID, icmp_ln119_2_reg_620_pp0_iter17_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter18 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln119_2_reg_620_pp0_iter17_reg = ap_const_lv1_1))) then 
            gmem0_blk_n_B <= m_axi_gmem0_0_BVALID;
        else 
            gmem0_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    gmem0_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter13, m_axi_gmem0_0_WREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            gmem0_blk_n_W <= m_axi_gmem0_0_WREADY;
        else 
            gmem0_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;


    gmem2_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter4, m_axi_gmem2_0_ARREADY, or_ln117_reg_616_pp0_iter3_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (or_ln117_reg_616_pp0_iter3_reg = ap_const_lv1_1))) then 
            gmem2_blk_n_AR <= m_axi_gmem2_0_ARREADY;
        else 
            gmem2_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem2_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter12, m_axi_gmem2_0_RVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            gmem2_blk_n_R <= m_axi_gmem2_0_RVALID;
        else 
            gmem2_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln115_fu_234_p2 <= "1" when (indvar_flatten57_fu_114 = mul_ln112_1) else "0";
    icmp_ln117_fu_245_p2 <= "1" when (indvar_flatten35_fu_106 = mul_ln112) else "0";
    icmp_ln119_1_fu_261_p2 <= "1" when (ow_fu_98 = in_w) else "0";
    icmp_ln119_2_fu_300_p2 <= "1" when (select_ln119_fu_292_p3 = in_w) else "0";
    icmp_ln119_fu_256_p2 <= "1" when (in_w = ap_const_lv8_0) else "0";
    m_axi_gmem0_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem0_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem0_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem0_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem0_0_AWADDR <= gmem0_addr_reg_650;
    m_axi_gmem0_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_0_AWLEN <= zext_ln119_cast_reg_590(32 - 1 downto 0);
    m_axi_gmem0_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_0_AWUSER <= ap_const_lv1_0;

    m_axi_gmem0_0_AWVALID_assign_proc : process(ap_enable_reg_pp0_iter4, or_ln117_reg_616_pp0_iter3_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (or_ln117_reg_616_pp0_iter3_reg = ap_const_lv1_1))) then 
            m_axi_gmem0_0_AWVALID <= ap_const_logic_1;
        else 
            m_axi_gmem0_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem0_0_BREADY_assign_proc : process(ap_enable_reg_pp0_iter18, icmp_ln119_2_reg_620_pp0_iter17_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter18 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln119_2_reg_620_pp0_iter17_reg = ap_const_lv1_1))) then 
            m_axi_gmem0_0_BREADY <= ap_const_logic_1;
        else 
            m_axi_gmem0_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_0_RREADY <= ap_const_logic_0;
    m_axi_gmem0_0_WDATA <= gmem2_addr_read_reg_661;
    m_axi_gmem0_0_WID <= ap_const_lv1_0;
    m_axi_gmem0_0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_0_WSTRB <= ap_const_lv1_1;
    m_axi_gmem0_0_WUSER <= ap_const_lv1_0;

    m_axi_gmem0_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_gmem0_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem0_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem2_0_ARADDR <= gmem2_addr_reg_644;
    m_axi_gmem2_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem2_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem2_0_ARID <= ap_const_lv1_0;
    m_axi_gmem2_0_ARLEN <= zext_ln119_cast_reg_590(32 - 1 downto 0);
    m_axi_gmem2_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem2_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem2_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem2_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem2_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem2_0_ARUSER <= ap_const_lv1_0;

    m_axi_gmem2_0_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter4, or_ln117_reg_616_pp0_iter3_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (or_ln117_reg_616_pp0_iter3_reg = ap_const_lv1_1))) then 
            m_axi_gmem2_0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem2_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem2_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem2_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem2_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem2_0_AWID <= ap_const_lv1_0;
    m_axi_gmem2_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem2_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem2_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem2_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem2_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem2_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem2_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem2_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem2_0_BREADY <= ap_const_logic_0;

    m_axi_gmem2_0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_gmem2_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem2_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem2_0_WDATA <= ap_const_lv8_0;
    m_axi_gmem2_0_WID <= ap_const_lv1_0;
    m_axi_gmem2_0_WLAST <= ap_const_logic_0;
    m_axi_gmem2_0_WSTRB <= ap_const_lv1_0;
    m_axi_gmem2_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem2_0_WVALID <= ap_const_logic_0;
    or_ln115_fu_250_p2 <= (icmp_ln117_fu_245_p2 or ap_phi_mux_first_iter_2_phi_fu_188_p4);
    or_ln117_fu_274_p2 <= (select_ln115_4_fu_266_p3 or or_ln115_fu_250_p2);
    or_ln119_fu_286_p2 <= (select_ln115_4_fu_266_p3 or icmp_ln117_fu_245_p2);
    select_ln115_1_fu_427_p3 <= 
        shl_ln119_mid1_fu_416_p3 when (icmp_ln117_reg_600_pp0_iter2_reg(0) = '1') else 
        shl_ln1_fu_383_p3;
    select_ln115_2_fu_438_p3 <= 
        ap_const_lv14_0 when (icmp_ln117_reg_600_pp0_iter2_reg(0) = '1') else 
        shl_ln119_1_fu_394_p3;
    select_ln115_3_fu_450_p3 <= 
        add_ln119_4_fu_445_p2 when (icmp_ln117_reg_600_pp0_iter2_reg(0) = '1') else 
        add_ln119_1_fu_410_p2;
    select_ln115_4_fu_266_p3 <= 
        icmp_ln119_fu_256_p2 when (icmp_ln117_fu_245_p2(0) = '1') else 
        icmp_ln119_1_fu_261_p2;
    select_ln115_5_fu_353_p3 <= 
        add_ln115_1_fu_347_p2 when (icmp_ln117_reg_600(0) = '1') else 
        oc_1_fu_110;
    select_ln115_fu_340_p3 <= 
        ap_const_lv8_0 when (icmp_ln117_reg_600(0) = '1') else 
        oh_1_fu_102;
    select_ln117_1_fu_490_p3 <= 
        add_ln119_6_fu_484_p2 when (select_ln115_4_reg_609_pp0_iter2_reg(0) = '1') else 
        select_ln115_3_fu_450_p3;
    select_ln117_2_fu_366_p3 <= 
        add_ln117_fu_360_p2 when (select_ln115_4_reg_609(0) = '1') else 
        select_ln115_fu_340_p3;
    select_ln117_3_fu_311_p3 <= 
        ap_const_lv16_1 when (icmp_ln117_fu_245_p2(0) = '1') else 
        add_ln117_1_fu_305_p2;
    select_ln117_fu_468_p3 <= 
        shl_ln119_1_mid1_fu_457_p3 when (select_ln115_4_reg_609_pp0_iter2_reg(0) = '1') else 
        select_ln115_2_fu_438_p3;
    select_ln119_fu_292_p3 <= 
        ap_const_lv8_1 when (or_ln119_fu_286_p2(0) = '1') else 
        add_ln119_7_fu_280_p2;
    shl_ln119_1_fu_394_p3 <= (oh_reg_624 & ap_const_lv6_0);
    shl_ln119_1_mid1_fu_457_p3 <= (add_ln117_reg_639 & ap_const_lv6_0);
    shl_ln119_mid1_fu_416_p3 <= (add_ln115_1_reg_634 & ap_const_lv12_0);
    shl_ln1_fu_383_p3 <= (oc_reg_629 & ap_const_lv12_0);
    zext_ln115_fu_434_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln115_1_fu_427_p3),64));
    zext_ln117_1_fu_423_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln119_mid1_fu_416_p3),64));
    zext_ln117_fu_390_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_383_p3),64));
    zext_ln119_1_fu_401_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln119_1_fu_394_p3),64));
    zext_ln119_2_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln119_1_mid1_fu_457_p3),64));
    zext_ln119_3_fu_475_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln117_fu_468_p3),64));
    zext_ln119_cast_fu_196_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln119),64));
end behav;
