-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dpu_conv_top_dpu_conv_top_Pipeline_POOL_OC_POOL_H_POOL_W is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem2_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem2_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem2_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem2_0_WREADY : IN STD_LOGIC;
    m_axi_gmem2_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem2_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem2_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem2_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem2_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_RVALID : IN STD_LOGIC;
    m_axi_gmem2_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem2_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem2_0_RLAST : IN STD_LOGIC;
    m_axi_gmem2_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem2_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_BVALID : IN STD_LOGIC;
    m_axi_gmem2_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem2_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    ofmap : IN STD_LOGIC_VECTOR (63 downto 0);
    mul_ln82_1 : IN STD_LOGIC_VECTOR (21 downto 0);
    conv_scratch : IN STD_LOGIC_VECTOR (63 downto 0);
    lshr_ln1 : IN STD_LOGIC_VECTOR (6 downto 0);
    zext_ln85 : IN STD_LOGIC_VECTOR (6 downto 0);
    mul_ln82 : IN STD_LOGIC_VECTOR (13 downto 0) );
end;


architecture behav of dpu_conv_top_dpu_conv_top_Pipeline_POOL_OC_POOL_H_POOL_W is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv22_1 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv9_40 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal icmp_ln85_reg_678 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_720 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op113_writereq_state4 : BOOLEAN;
    signal ap_block_state4_io_grp1 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage3_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_state4_io_grp2 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone_grp2_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage3_subdone_grp2 : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage3_subdone_grp4_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage3_subdone_grp4 : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage3 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem0_blk_n_B : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_grp9 : BOOLEAN;
    signal icmp_ln89_2_reg_753 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln89_2_reg_753_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage1_subdone_grp9_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp9 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal gmem0_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0_grp8 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp8_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp8 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal gmem0_blk_n_AW : STD_LOGIC;
    signal ap_block_pp0_stage3_grp1 : BOOLEAN;
    signal gmem2_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage3_grp2 : BOOLEAN;
    signal gmem2_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage3_grp4 : BOOLEAN;
    signal ap_block_pp0_stage0_grp5 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp5_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp5 : BOOLEAN;
    signal ap_block_pp0_stage1_grp3 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp3_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp3 : BOOLEAN;
    signal ap_block_pp0_stage1_grp6 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp6_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp6 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_grp7 : BOOLEAN;
    signal reg_195 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage3_11001_grp4 : BOOLEAN;
    signal ap_block_pp0_stage2_11001_grp7 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal zext_ln85_cast_fu_199_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln85_cast_reg_663 : STD_LOGIC_VECTOR (63 downto 0);
    signal oh_1_reg_668 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_state22_pp0_stage1_iter5_grp9 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal shl_ln_fu_240_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal shl_ln_reg_673 : STD_LOGIC_VECTOR (19 downto 0);
    signal icmp_ln85_fu_248_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln85_reg_678_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln85_reg_678_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln85_reg_678_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln87_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln87_reg_682 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln85_fu_267_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln85_reg_687 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln91_mid1_fu_281_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal shl_ln91_mid1_reg_692 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln85_1_fu_297_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln85_1_reg_697 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln85_3_fu_311_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln85_3_reg_702 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln87_fu_327_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln87_reg_708 : STD_LOGIC_VECTOR (6 downto 0);
    signal ow_mid2_fu_339_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ow_mid2_reg_714 : STD_LOGIC_VECTOR (6 downto 0);
    signal first_iter_0_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln91_fu_353_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln91_reg_724 : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem0_addr_reg_730 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage2_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal gmem2_addr_reg_735 : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem2_addr_1_reg_741 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln89_2_fu_548_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln89_2_reg_753_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln89_2_reg_753_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln89_2_reg_753_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p01_reg_757 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001_grp5 : BOOLEAN;
    signal p10_reg_763 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage1_11001_grp6 : BOOLEAN;
    signal m0_fu_568_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal m0_reg_769 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln98_fu_592_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln98_reg_775 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage3_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage3_subdone_grp0 : BOOLEAN;
    signal add_ln91_2_mid2_fu_448_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2_grp0 : BOOLEAN;
    signal add_ln91_7_fu_519_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln91_5_fu_508_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage3_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage3_11001_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp8 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp8 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp9 : BOOLEAN;
    signal ow_fu_108 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln89_fu_543_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal oh_fu_112 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal select_ln87_fu_455_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten_fu_116 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    signal select_ln87_1_fu_364_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal oc_fu_120 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln85_4_fu_319_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten25_fu_124 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    signal add_ln85_fu_253_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal add_ln85_1_fu_275_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln85_1_fu_289_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal icmp_ln89_fu_301_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln89_1_fu_306_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_67_fu_333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln87_1_fu_358_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln91_3_fu_390_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln91_1_fu_397_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln91_1_fu_401_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln91_fu_387_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln91_5_fu_412_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln91_8_fu_415_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln91_2_fu_406_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln91_3_mid1_fu_427_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln91_6_fu_434_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln91_9_fu_438_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln91_10_fu_443_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln85_2_fu_420_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln91_1_fu_466_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln91_2_fu_478_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln89_fu_474_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln91_3_fu_489_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln91_4_fu_498_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln91_4_fu_504_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln91_3_fu_493_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln91_2_fu_485_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln91_6_fu_514_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln96_fu_563_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage3_grp0 : BOOLEAN;
    signal icmp_ln97_fu_575_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal m1_fu_580_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln98_fu_587_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal ap_condition_exit_pp0_iter4_stage1 : STD_LOGIC;
    signal ap_idle_pp0_0to3 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_done_pending_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dpu_conv_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component dpu_conv_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage3,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp5_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp5_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp5_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5)) then 
                        ap_block_pp0_stage0_subdone_grp5_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp8_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp8_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp8_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8)) then 
                        ap_block_pp0_stage0_subdone_grp8_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp3_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp3_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp3_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3)) then 
                        ap_block_pp0_stage1_subdone_grp3_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp6_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp6_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp6_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp6)) then 
                        ap_block_pp0_stage1_subdone_grp6_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp9_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp9_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp9_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp9)) then 
                        ap_block_pp0_stage1_subdone_grp9_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage2_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then 
                        ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0)) then 
                        ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage3_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage3_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then 
                        ap_block_pp0_stage3_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp0)) then 
                        ap_block_pp0_stage3_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage3_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage3_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then 
                        ap_block_pp0_stage3_subdone_grp1_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp1)) then 
                        ap_block_pp0_stage3_subdone_grp1_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage3_subdone_grp2_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage3_subdone_grp2_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then 
                        ap_block_pp0_stage3_subdone_grp2_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2)) then 
                        ap_block_pp0_stage3_subdone_grp2_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage3_subdone_grp4_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage3_subdone_grp4_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then 
                        ap_block_pp0_stage3_subdone_grp4_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp4)) then 
                        ap_block_pp0_stage3_subdone_grp4_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage3)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to3 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to3 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage1))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to3 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage1))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter4_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to3 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage1))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
            end if; 
        end if;
    end process;

    indvar_flatten25_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                indvar_flatten25_fu_124 <= ap_const_lv22_0;
            elsif (((icmp_ln85_fu_248_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                indvar_flatten25_fu_124 <= add_ln85_fu_253_p2;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                indvar_flatten_fu_116 <= ap_const_lv14_0;
            elsif (((icmp_ln85_fu_248_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                indvar_flatten_fu_116 <= select_ln87_1_fu_364_p3;
            end if; 
        end if;
    end process;

    oc_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                oc_fu_120 <= ap_const_lv8_0;
            elsif (((icmp_ln85_fu_248_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                oc_fu_120 <= select_ln85_4_fu_319_p3;
            end if; 
        end if;
    end process;

    oh_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                oh_fu_112 <= ap_const_lv7_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp7) and (icmp_ln85_reg_678 = ap_const_lv1_0))) then 
                oh_fu_112 <= select_ln87_fu_455_p3;
            end if; 
        end if;
    end process;

    ow_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                ow_fu_108 <= ap_const_lv7_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0) and (icmp_ln85_reg_678 = ap_const_lv1_0))) then 
                ow_fu_108 <= add_ln89_fu_543_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                add_ln87_reg_708 <= add_ln87_fu_327_p2;
                add_ln91_reg_724 <= add_ln91_fu_353_p2;
                first_iter_0_reg_720 <= first_iter_0_fu_347_p2;
                icmp_ln85_reg_678 <= icmp_ln85_fu_248_p2;
                icmp_ln85_reg_678_pp0_iter1_reg <= icmp_ln85_reg_678;
                icmp_ln85_reg_678_pp0_iter2_reg <= icmp_ln85_reg_678_pp0_iter1_reg;
                icmp_ln85_reg_678_pp0_iter3_reg <= icmp_ln85_reg_678_pp0_iter2_reg;
                icmp_ln87_reg_682 <= icmp_ln87_fu_262_p2;
                oh_1_reg_668 <= oh_fu_112;
                ow_mid2_reg_714 <= ow_mid2_fu_339_p3;
                select_ln85_3_reg_702 <= select_ln85_3_fu_311_p3;
                select_ln85_reg_687 <= select_ln85_fu_267_p3;
                    shl_ln91_mid1_reg_692(19 downto 12) <= shl_ln91_mid1_fu_281_p3(19 downto 12);
                    shl_ln_reg_673(19 downto 12) <= shl_ln_fu_240_p3(19 downto 12);
                    zext_ln85_1_reg_697(19 downto 12) <= zext_ln85_1_fu_297_p1(19 downto 12);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0))) then
                gmem0_addr_reg_730 <= add_ln91_2_mid2_fu_448_p3;
                icmp_ln89_2_reg_753 <= icmp_ln89_2_fu_548_p2;
                icmp_ln89_2_reg_753_pp0_iter1_reg <= icmp_ln89_2_reg_753;
                icmp_ln89_2_reg_753_pp0_iter2_reg <= icmp_ln89_2_reg_753_pp0_iter1_reg;
                icmp_ln89_2_reg_753_pp0_iter3_reg <= icmp_ln89_2_reg_753_pp0_iter2_reg;
                icmp_ln89_2_reg_753_pp0_iter4_reg <= icmp_ln89_2_reg_753_pp0_iter3_reg;
                m0_reg_769 <= m0_fu_568_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp7))) then
                gmem2_addr_1_reg_741 <= add_ln91_5_fu_508_p2;
                gmem2_addr_reg_735 <= add_ln91_7_fu_519_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg))) then
                p01_reg_757 <= m_axi_gmem2_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp6_done_reg))) then
                p10_reg_763 <= m_axi_gmem2_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp7)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp4_done_reg)))) then
                reg_195 <= m_axi_gmem2_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp0))) then
                select_ln98_reg_775 <= select_ln98_fu_592_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                    zext_ln85_cast_reg_663(6 downto 0) <= zext_ln85_cast_fu_199_p1(6 downto 0);
            end if;
        end if;
    end process;
    zext_ln85_cast_reg_663(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";
    shl_ln_reg_673(11 downto 0) <= "000000000000";
    shl_ln91_mid1_reg_692(11 downto 0) <= "000000000000";
    zext_ln85_1_reg_697(11 downto 0) <= "000000000000";
    zext_ln85_1_reg_697(63 downto 20) <= "00000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage3_subdone, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_block_pp0_stage2_subdone, ap_condition_exit_pp0_iter4_stage1, ap_idle_pp0_0to3, ap_done_pending_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_done_pending_pp0 = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if (((ap_idle_pp0_0to3 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln85_1_fu_275_p2 <= std_logic_vector(unsigned(oc_fu_120) + unsigned(ap_const_lv8_1));
    add_ln85_fu_253_p2 <= std_logic_vector(unsigned(indvar_flatten25_fu_124) + unsigned(ap_const_lv22_1));
    add_ln87_1_fu_358_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_116) + unsigned(ap_const_lv14_1));
    add_ln87_fu_327_p2 <= std_logic_vector(unsigned(select_ln85_fu_267_p3) + unsigned(ap_const_lv7_1));
    add_ln89_fu_543_p2 <= std_logic_vector(unsigned(ow_mid2_reg_714) + unsigned(ap_const_lv7_1));
    add_ln91_10_fu_443_p2 <= std_logic_vector(unsigned(add_ln91_9_fu_438_p2) + unsigned(zext_ln85_1_reg_697));
    add_ln91_1_fu_401_p2 <= std_logic_vector(unsigned(zext_ln91_1_fu_397_p1) + unsigned(ofmap));
    add_ln91_2_fu_406_p2 <= std_logic_vector(unsigned(add_ln91_1_fu_401_p2) + unsigned(zext_ln91_fu_387_p1));
    add_ln91_2_mid2_fu_448_p3 <= 
        add_ln91_10_fu_443_p2 when (select_ln85_3_reg_702(0) = '1') else 
        select_ln85_2_fu_420_p3;
    add_ln91_3_fu_493_p2 <= std_logic_vector(unsigned(add_ln91_reg_724) + unsigned(zext_ln89_fu_474_p1));
    add_ln91_4_fu_498_p2 <= std_logic_vector(unsigned(zext_ln91_3_fu_489_p1) + unsigned(ap_const_lv9_40));
    add_ln91_5_fu_508_p2 <= std_logic_vector(unsigned(zext_ln91_4_fu_504_p1) + unsigned(add_ln91_3_fu_493_p2));
    add_ln91_6_fu_514_p2 <= std_logic_vector(unsigned(add_ln91_reg_724) + unsigned(zext_ln91_2_fu_485_p1));
    add_ln91_7_fu_519_p2 <= std_logic_vector(unsigned(add_ln91_6_fu_514_p2) + unsigned(zext_ln89_fu_474_p1));
    add_ln91_8_fu_415_p2 <= std_logic_vector(unsigned(zext_ln91_5_fu_412_p1) + unsigned(ofmap));
    add_ln91_9_fu_438_p2 <= std_logic_vector(unsigned(zext_ln91_6_fu_434_p1) + unsigned(ofmap));
    add_ln91_fu_353_p2 <= std_logic_vector(unsigned(zext_ln85_1_fu_297_p1) + unsigned(conv_scratch));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
        ap_block_pp0_stage0_01001_grp8 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp5_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem2_0_RVALID, ap_block_pp0_stage0_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp5 <= ((m_axi_gmem2_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp8_assign_proc : process(ap_enable_reg_pp0_iter4, m_axi_gmem0_0_WREADY, ap_block_pp0_stage0_subdone_grp8_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp8 <= ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg) and (m_axi_gmem0_0_WREADY = ap_const_logic_0));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, m_axi_gmem2_0_RVALID, m_axi_gmem0_0_WREADY, ap_block_pp0_stage0_subdone_grp8_done_reg, ap_block_pp0_stage0_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg) and (m_axi_gmem0_0_WREADY = ap_const_logic_0)) or ((m_axi_gmem2_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_grp5_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem2_0_RVALID, ap_block_pp0_stage0_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp5 <= ((m_axi_gmem2_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp8_assign_proc : process(ap_enable_reg_pp0_iter4, m_axi_gmem0_0_WREADY, ap_block_pp0_stage0_subdone_grp8_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp8 <= ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg) and (m_axi_gmem0_0_WREADY = ap_const_logic_0));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter5, m_axi_gmem2_0_ARREADY, m_axi_gmem2_0_RVALID, ap_block_pp0_stage1_subdone_grp9_done_reg, ap_block_pp0_stage1_subdone_grp3_done_reg, ap_block_pp0_stage1_subdone_grp6_done_reg, ap_block_state22_pp0_stage1_iter5_grp9)
    begin
                ap_block_pp0_stage1_11001 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state22_pp0_stage1_iter5_grp9) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp9_done_reg)) or ((m_axi_gmem2_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp6_done_reg)) or ((m_axi_gmem2_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg)));
    end process;


    ap_block_pp0_stage1_11001_grp3_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem2_0_ARREADY, ap_block_pp0_stage1_subdone_grp3_done_reg)
    begin
                ap_block_pp0_stage1_11001_grp3 <= ((m_axi_gmem2_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg));
    end process;


    ap_block_pp0_stage1_11001_grp6_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem2_0_RVALID, ap_block_pp0_stage1_subdone_grp6_done_reg)
    begin
                ap_block_pp0_stage1_11001_grp6 <= ((m_axi_gmem2_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp6_done_reg));
    end process;


    ap_block_pp0_stage1_11001_grp9_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage1_subdone_grp9_done_reg, ap_block_state22_pp0_stage1_iter5_grp9)
    begin
                ap_block_pp0_stage1_11001_grp9 <= ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state22_pp0_stage1_iter5_grp9) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp9_done_reg));
    end process;

        ap_block_pp0_stage1_grp3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp9 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter5, m_axi_gmem2_0_ARREADY, m_axi_gmem2_0_RVALID, ap_block_pp0_stage1_subdone_grp9_done_reg, ap_block_pp0_stage1_subdone_grp3_done_reg, ap_block_pp0_stage1_subdone_grp6_done_reg, ap_block_state22_pp0_stage1_iter5_grp9)
    begin
                ap_block_pp0_stage1_subdone <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state22_pp0_stage1_iter5_grp9) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp9_done_reg)) or ((m_axi_gmem2_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp6_done_reg)) or ((m_axi_gmem2_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg)));
    end process;


    ap_block_pp0_stage1_subdone_grp3_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem2_0_ARREADY, ap_block_pp0_stage1_subdone_grp3_done_reg)
    begin
                ap_block_pp0_stage1_subdone_grp3 <= ((m_axi_gmem2_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg));
    end process;


    ap_block_pp0_stage1_subdone_grp6_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem2_0_RVALID, ap_block_pp0_stage1_subdone_grp6_done_reg)
    begin
                ap_block_pp0_stage1_subdone_grp6 <= ((m_axi_gmem2_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp6_done_reg));
    end process;


    ap_block_pp0_stage1_subdone_grp9_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage1_subdone_grp9_done_reg, ap_block_state22_pp0_stage1_iter5_grp9)
    begin
                ap_block_pp0_stage1_subdone_grp9 <= ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state22_pp0_stage1_iter5_grp9) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp9_done_reg));
    end process;

        ap_block_pp0_stage2_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_11001_grp7_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem2_0_RVALID)
    begin
                ap_block_pp0_stage2_11001_grp7 <= ((m_axi_gmem2_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage2_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_grp7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem2_0_RVALID)
    begin
                ap_block_pp0_stage2_subdone <= ((m_axi_gmem2_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage2_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_11001_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem2_0_RVALID, ap_block_state4_io_grp1, ap_block_pp0_stage3_subdone_grp1_done_reg, ap_block_state4_io_grp2, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage3_subdone_grp4_done_reg)
    begin
                ap_block_pp0_stage3_11001 <= (((m_axi_gmem2_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp4_done_reg)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (((ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg)) or ((ap_const_boolean_1 = ap_block_state4_io_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp1_done_reg)))));
    end process;

        ap_block_pp0_stage3_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_11001_grp1_assign_proc : process(ap_block_state4_io_grp1, ap_block_pp0_stage3_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage3_11001_grp1 <= ((ap_const_boolean_1 = ap_block_state4_io_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp1_done_reg));
    end process;


    ap_block_pp0_stage3_11001_grp2_assign_proc : process(ap_block_state4_io_grp2, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage3_11001_grp2 <= ((ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg));
    end process;


    ap_block_pp0_stage3_11001_grp4_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem2_0_RVALID, ap_block_pp0_stage3_subdone_grp4_done_reg)
    begin
                ap_block_pp0_stage3_11001_grp4 <= ((m_axi_gmem2_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp4_done_reg));
    end process;

        ap_block_pp0_stage3_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_grp4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem2_0_RVALID, ap_block_state4_io_grp1, ap_block_pp0_stage3_subdone_grp1_done_reg, ap_block_state4_io_grp2, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage3_subdone_grp4_done_reg)
    begin
                ap_block_pp0_stage3_subdone <= (((m_axi_gmem2_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp4_done_reg)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (((ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg)) or ((ap_const_boolean_1 = ap_block_state4_io_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp1_done_reg)))));
    end process;

        ap_block_pp0_stage3_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_subdone_grp1_assign_proc : process(ap_block_state4_io_grp1, ap_block_pp0_stage3_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage3_subdone_grp1 <= ((ap_const_boolean_1 = ap_block_state4_io_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp1_done_reg));
    end process;


    ap_block_pp0_stage3_subdone_grp2_assign_proc : process(ap_block_state4_io_grp2, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage3_subdone_grp2 <= ((ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg));
    end process;


    ap_block_pp0_stage3_subdone_grp4_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem2_0_RVALID, ap_block_pp0_stage3_subdone_grp4_done_reg)
    begin
                ap_block_pp0_stage3_subdone_grp4 <= ((m_axi_gmem2_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp4_done_reg));
    end process;


    ap_block_state22_pp0_stage1_iter5_grp9_assign_proc : process(m_axi_gmem0_0_BVALID, icmp_ln89_2_reg_753_pp0_iter4_reg)
    begin
                ap_block_state22_pp0_stage1_iter5_grp9 <= ((icmp_ln89_2_reg_753_pp0_iter4_reg = ap_const_lv1_1) and (m_axi_gmem0_0_BVALID = ap_const_logic_0));
    end process;


    ap_block_state4_io_grp1_assign_proc : process(m_axi_gmem0_0_AWREADY, ap_predicate_op113_writereq_state4)
    begin
                ap_block_state4_io_grp1 <= ((ap_predicate_op113_writereq_state4 = ap_const_boolean_1) and (m_axi_gmem0_0_AWREADY = ap_const_logic_0));
    end process;


    ap_block_state4_io_grp2_assign_proc : process(m_axi_gmem2_0_ARREADY, icmp_ln85_reg_678)
    begin
                ap_block_state4_io_grp2 <= ((m_axi_gmem2_0_ARREADY = ap_const_logic_0) and (icmp_ln85_reg_678 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage3_assign_proc : process(ap_CS_fsm_pp0_stage3, icmp_ln85_reg_678, ap_block_pp0_stage3_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (icmp_ln85_reg_678 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage3 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter4_stage1_assign_proc : process(ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln85_reg_678_pp0_iter3_reg)
    begin
        if (((icmp_ln85_reg_678_pp0_iter3_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_condition_exit_pp0_iter4_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter4_stage1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_done_pending_pp0_assign_proc : process(ap_loop_exit_ready, ap_loop_exit_ready_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (not(((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0) and (ap_loop_exit_ready = ap_const_logic_0)))) then 
            ap_done_pending_pp0 <= ap_const_logic_1;
        else 
            ap_done_pending_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to3_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to3 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage3;

    ap_predicate_op113_writereq_state4_assign_proc : process(icmp_ln85_reg_678, first_iter_0_reg_720)
    begin
                ap_predicate_op113_writereq_state4 <= ((first_iter_0_reg_720 = ap_const_lv1_1) and (icmp_ln85_reg_678 = ap_const_lv1_0));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    empty_67_fu_333_p2 <= (select_ln85_3_fu_311_p3 or icmp_ln87_fu_262_p2);
    first_iter_0_fu_347_p2 <= "1" when (ow_mid2_fu_339_p3 = ap_const_lv7_0) else "0";

    gmem0_blk_n_AW_assign_proc : process(ap_CS_fsm_pp0_stage3, m_axi_gmem0_0_AWREADY, ap_predicate_op113_writereq_state4, ap_block_pp0_stage3_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage3_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp1_done_reg) and (ap_predicate_op113_writereq_state4 = ap_const_boolean_1))) then 
            gmem0_blk_n_AW <= m_axi_gmem0_0_AWREADY;
        else 
            gmem0_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem0_blk_n_B_assign_proc : process(ap_enable_reg_pp0_iter5, m_axi_gmem0_0_BVALID, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_grp9, icmp_ln89_2_reg_753_pp0_iter4_reg, ap_block_pp0_stage1_subdone_grp9_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln89_2_reg_753_pp0_iter4_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp9_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp9))) then 
            gmem0_blk_n_B <= m_axi_gmem0_0_BVALID;
        else 
            gmem0_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    gmem0_blk_n_W_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, m_axi_gmem0_0_WREADY, ap_block_pp0_stage0_grp8, ap_block_pp0_stage0_subdone_grp8_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp8))) then 
            gmem0_blk_n_W <= m_axi_gmem0_0_WREADY;
        else 
            gmem0_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;


    gmem2_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage3, m_axi_gmem2_0_ARREADY, icmp_ln85_reg_678, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage3_grp2, ap_block_pp0_stage1_grp3, ap_block_pp0_stage1_subdone_grp3_done_reg)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg) and (icmp_ln85_reg_678 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp3)))) then 
            gmem2_blk_n_AR <= m_axi_gmem2_0_ARREADY;
        else 
            gmem2_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem2_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage3, m_axi_gmem2_0_RVALID, ap_block_pp0_stage3_subdone_grp4_done_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage3_grp4, ap_block_pp0_stage0_grp5, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_pp0_stage1_grp6, ap_block_pp0_stage1_subdone_grp6_done_reg, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_grp7)
    begin
        if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp7)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp6_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp6)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp5)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp4_done_reg)))) then 
            gmem2_blk_n_R <= m_axi_gmem2_0_RVALID;
        else 
            gmem2_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln85_fu_248_p2 <= "1" when (indvar_flatten25_fu_124 = mul_ln82_1) else "0";
    icmp_ln87_fu_262_p2 <= "1" when (indvar_flatten_fu_116 = mul_ln82) else "0";
    icmp_ln89_1_fu_306_p2 <= "1" when (ow_fu_108 = lshr_ln1) else "0";
    icmp_ln89_2_fu_548_p2 <= "1" when (add_ln89_fu_543_p2 = lshr_ln1) else "0";
    icmp_ln89_fu_301_p2 <= "1" when (lshr_ln1 = ap_const_lv7_0) else "0";
    icmp_ln96_fu_563_p2 <= "1" when (signed(reg_195) > signed(p01_reg_757)) else "0";
    icmp_ln97_fu_575_p2 <= "1" when (signed(p10_reg_763) > signed(reg_195)) else "0";
    icmp_ln98_fu_587_p2 <= "1" when (signed(m0_reg_769) > signed(m1_fu_580_p3)) else "0";
    m0_fu_568_p3 <= 
        reg_195 when (icmp_ln96_fu_563_p2(0) = '1') else 
        p01_reg_757;
    m1_fu_580_p3 <= 
        p10_reg_763 when (icmp_ln97_fu_575_p2(0) = '1') else 
        reg_195;
    m_axi_gmem0_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem0_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem0_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem0_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem0_0_AWADDR <= gmem0_addr_reg_730;
    m_axi_gmem0_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_0_AWLEN <= zext_ln85_cast_reg_663(32 - 1 downto 0);
    m_axi_gmem0_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_0_AWUSER <= ap_const_lv1_0;

    m_axi_gmem0_0_AWVALID_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_predicate_op113_writereq_state4, ap_block_pp0_stage3_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage3_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp1_done_reg) and (ap_predicate_op113_writereq_state4 = ap_const_boolean_1))) then 
            m_axi_gmem0_0_AWVALID <= ap_const_logic_1;
        else 
            m_axi_gmem0_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem0_0_BREADY_assign_proc : process(ap_enable_reg_pp0_iter5, ap_CS_fsm_pp0_stage1, icmp_ln89_2_reg_753_pp0_iter4_reg, ap_block_pp0_stage1_subdone_grp9_done_reg, ap_block_pp0_stage1_11001_grp9)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln89_2_reg_753_pp0_iter4_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp9) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp9_done_reg))) then 
            m_axi_gmem0_0_BREADY <= ap_const_logic_1;
        else 
            m_axi_gmem0_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_0_RREADY <= ap_const_logic_0;
    m_axi_gmem0_0_WDATA <= select_ln98_reg_775;
    m_axi_gmem0_0_WID <= ap_const_lv1_0;
    m_axi_gmem0_0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_0_WSTRB <= ap_const_lv1_1;
    m_axi_gmem0_0_WUSER <= ap_const_lv1_0;

    m_axi_gmem0_0_WVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_subdone_grp8_done_reg, ap_block_pp0_stage0_11001_grp8)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp8) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg))) then 
            m_axi_gmem0_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem0_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem2_0_ARADDR_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage3, icmp_ln85_reg_678, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp3_done_reg, gmem2_addr_reg_735, gmem2_addr_1_reg_741, ap_block_pp0_stage3_11001_grp2, ap_block_pp0_stage1_11001_grp3)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg))) then 
            m_axi_gmem2_0_ARADDR <= gmem2_addr_1_reg_741;
        elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg) and (icmp_ln85_reg_678 = ap_const_lv1_0))) then 
            m_axi_gmem2_0_ARADDR <= gmem2_addr_reg_735;
        else 
            m_axi_gmem2_0_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    m_axi_gmem2_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem2_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem2_0_ARID <= ap_const_lv1_0;
    m_axi_gmem2_0_ARLEN <= ap_const_lv64_2(32 - 1 downto 0);
    m_axi_gmem2_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem2_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem2_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem2_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem2_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem2_0_ARUSER <= ap_const_lv1_0;

    m_axi_gmem2_0_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage3, icmp_ln85_reg_678, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp3_done_reg, ap_block_pp0_stage3_11001_grp2, ap_block_pp0_stage1_11001_grp3)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg) and (icmp_ln85_reg_678 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg)))) then 
            m_axi_gmem2_0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem2_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem2_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem2_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem2_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem2_0_AWID <= ap_const_lv1_0;
    m_axi_gmem2_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem2_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem2_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem2_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem2_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem2_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem2_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem2_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem2_0_BREADY <= ap_const_logic_0;

    m_axi_gmem2_0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone_grp4_done_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_pp0_stage1_subdone_grp6_done_reg, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage3_11001_grp4, ap_block_pp0_stage2_11001_grp7, ap_block_pp0_stage0_11001_grp5, ap_block_pp0_stage1_11001_grp6)
    begin
        if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp7)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp6_done_reg)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp4_done_reg)))) then 
            m_axi_gmem2_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem2_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem2_0_WDATA <= ap_const_lv8_0;
    m_axi_gmem2_0_WID <= ap_const_lv1_0;
    m_axi_gmem2_0_WLAST <= ap_const_logic_0;
    m_axi_gmem2_0_WSTRB <= ap_const_lv1_0;
    m_axi_gmem2_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem2_0_WVALID <= ap_const_logic_0;
    ow_mid2_fu_339_p3 <= 
        ap_const_lv7_0 when (empty_67_fu_333_p2(0) = '1') else 
        ow_fu_108;
    select_ln85_1_fu_289_p3 <= 
        shl_ln91_mid1_fu_281_p3 when (icmp_ln87_fu_262_p2(0) = '1') else 
        shl_ln_fu_240_p3;
    select_ln85_2_fu_420_p3 <= 
        add_ln91_8_fu_415_p2 when (icmp_ln87_reg_682(0) = '1') else 
        add_ln91_2_fu_406_p2;
    select_ln85_3_fu_311_p3 <= 
        icmp_ln89_fu_301_p2 when (icmp_ln87_fu_262_p2(0) = '1') else 
        icmp_ln89_1_fu_306_p2;
    select_ln85_4_fu_319_p3 <= 
        add_ln85_1_fu_275_p2 when (icmp_ln87_fu_262_p2(0) = '1') else 
        oc_fu_120;
    select_ln85_fu_267_p3 <= 
        ap_const_lv7_0 when (icmp_ln87_fu_262_p2(0) = '1') else 
        oh_fu_112;
    select_ln87_1_fu_364_p3 <= 
        ap_const_lv14_1 when (icmp_ln87_fu_262_p2(0) = '1') else 
        add_ln87_1_fu_358_p2;
    select_ln87_fu_455_p3 <= 
        add_ln87_reg_708 when (select_ln85_3_reg_702(0) = '1') else 
        select_ln85_reg_687;
    select_ln98_fu_592_p3 <= 
        m0_reg_769 when (icmp_ln98_fu_587_p2(0) = '1') else 
        m1_fu_580_p3;
    shl_ln91_1_fu_466_p3 <= (select_ln87_fu_455_p3 & ap_const_lv7_0);
    shl_ln91_2_fu_478_p3 <= (ow_mid2_reg_714 & ap_const_lv1_0);
    shl_ln91_3_fu_390_p3 <= (oh_1_reg_668 & ap_const_lv6_0);
    shl_ln91_3_mid1_fu_427_p3 <= (add_ln87_reg_708 & ap_const_lv6_0);
    shl_ln91_mid1_fu_281_p3 <= (add_ln85_1_fu_275_p2 & ap_const_lv12_0);
    shl_ln_fu_240_p3 <= (oc_fu_120 & ap_const_lv12_0);
    zext_ln85_1_fu_297_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln85_1_fu_289_p3),64));
    zext_ln85_cast_fu_199_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln85),64));
    zext_ln89_fu_474_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln91_1_fu_466_p3),64));
    zext_ln91_1_fu_397_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln91_3_fu_390_p3),64));
    zext_ln91_2_fu_485_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln91_2_fu_478_p3),64));
    zext_ln91_3_fu_489_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln91_2_fu_478_p3),9));
    zext_ln91_4_fu_504_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln91_4_fu_498_p2),64));
    zext_ln91_5_fu_412_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln91_mid1_reg_692),64));
    zext_ln91_6_fu_434_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln91_3_mid1_fu_427_p3),64));
    zext_ln91_fu_387_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_reg_673),64));
end behav;
