-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity speakable_cnn_top_partselect_8ns_64ns_6ns_8_1_1 is
generic (
    ADDRWIDTH : INTEGER := 6;
    DATAWIDTH : INTEGER := 64;
    DATA1WIDTH : INTEGER := 8
);
port (

    sel   : in std_logic_vector (ADDRWIDTH-1 downto 0);
    din   : in std_logic_vector (DATAWIDTH-1 downto 0);
    dout  : out std_logic_vector (DATA1WIDTH-1 downto 0)
);
end entity;

architecture behav of speakable_cnn_top_partselect_8ns_64ns_6ns_8_1_1 is
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of behav: architecture is "yes";
    signal concatenate : std_logic_vector (DATA1WIDTH-1 downto 0);    
    signal dout_tmp : std_logic_vector (DATA1WIDTH-1 downto 0);




begin

    concatenate <= (others => '0');
    process (din,sel) is
        variable din_tmp : std_logic_vector (DATAWIDTH+DATA1WIDTH-1 downto 0);
    begin
        din_tmp := concatenate & din;
        if to_integer(unsigned(sel)) >= din'low and to_integer(unsigned(sel)) <= din'high then
            dout_tmp <= din_tmp(to_integer(unsigned(sel))+DATA1WIDTH-1 downto to_integer(unsigned(sel)));
        end if;
    end process;




    dout <= dout_tmp;




end architecture;
