-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity speakable_cnn_top_speakable_cnn_top_Pipeline_LOAD_BIAS is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem1_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_WREADY : IN STD_LOGIC;
    m_axi_gmem1_0_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem1_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RVALID : IN STD_LOGIC;
    m_axi_gmem1_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_0_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_RLAST : IN STD_LOGIC;
    m_axi_gmem1_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem1_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_BVALID : IN STD_LOGIC;
    m_axi_gmem1_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    out_ch : IN STD_LOGIC_VECTOR (7 downto 0);
    bias : IN STD_LOGIC_VECTOR (63 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_7_ce0 : OUT STD_LOGIC;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_7_we0 : OUT STD_LOGIC;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_6_ce0 : OUT STD_LOGIC;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_6_we0 : OUT STD_LOGIC;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_5_ce0 : OUT STD_LOGIC;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_5_we0 : OUT STD_LOGIC;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_4_ce0 : OUT STD_LOGIC;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_4_we0 : OUT STD_LOGIC;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_3_ce0 : OUT STD_LOGIC;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_3_we0 : OUT STD_LOGIC;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_2_ce0 : OUT STD_LOGIC;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_2_we0 : OUT STD_LOGIC;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_1_ce0 : OUT STD_LOGIC;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_1_we0 : OUT STD_LOGIC;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_ce0 : OUT STD_LOGIC;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_we0 : OUT STD_LOGIC;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of speakable_cnn_top_speakable_cnn_top_Pipeline_LOAD_BIAS is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln30_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem1_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal gmem1_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln33_fu_256_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_reg_385 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_reg_385_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_reg_385_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_reg_385_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_reg_385_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_reg_385_pp0_iter5_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_reg_385_pp0_iter6_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_reg_385_pp0_iter7_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_reg_385_pp0_iter8_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_reg_385_pp0_iter9_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln_reg_389 : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln_reg_389_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln_reg_389_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln_reg_389_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln_reg_389_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln_reg_389_pp0_iter5_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln_reg_389_pp0_iter6_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln_reg_389_pp0_iter7_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln_reg_389_pp0_iter8_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln_reg_389_pp0_iter9_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_3_reg_394 : STD_LOGIC_VECTOR (60 downto 0);
    signal trunc_ln33_1_fu_298_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_1_reg_399 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_1_reg_399_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_1_reg_399_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_1_reg_399_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_1_reg_399_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_1_reg_399_pp0_iter5_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_1_reg_399_pp0_iter6_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_1_reg_399_pp0_iter7_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_1_reg_399_pp0_iter8_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln33_1_reg_399_pp0_iter9_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal gmem1_addr_read_reg_410 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln33_fu_335_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal sext_ln33_fu_325_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal oc_fu_104 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln30_fu_250_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_oc_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_1_we0_local : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal trunc_ln33_2_fu_362_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_1_ce0_local : STD_LOGIC;
    signal speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_2_we0_local : STD_LOGIC;
    signal speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_2_ce0_local : STD_LOGIC;
    signal speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_3_we0_local : STD_LOGIC;
    signal speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_3_ce0_local : STD_LOGIC;
    signal speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_4_we0_local : STD_LOGIC;
    signal speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_4_ce0_local : STD_LOGIC;
    signal speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_5_we0_local : STD_LOGIC;
    signal speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_5_ce0_local : STD_LOGIC;
    signal speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_6_we0_local : STD_LOGIC;
    signal speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_6_ce0_local : STD_LOGIC;
    signal speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_7_we0_local : STD_LOGIC;
    signal speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_7_ce0_local : STD_LOGIC;
    signal speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_we0_local : STD_LOGIC;
    signal speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_ce0_local : STD_LOGIC;
    signal shl_ln_fu_270_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln33_1_fu_278_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln33_fu_282_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln33_1_fu_346_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln33_2_fu_353_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lshr_ln33_fu_357_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component speakable_cnn_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component speakable_cnn_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    oc_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln30_fu_244_p2 = ap_const_lv1_0))) then 
                    oc_fu_104 <= add_ln30_fu_250_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    oc_fu_104 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                lshr_ln_reg_389 <= ap_sig_allocacmp_oc_1(5 downto 3);
                lshr_ln_reg_389_pp0_iter1_reg <= lshr_ln_reg_389;
                trunc_ln33_1_reg_399 <= trunc_ln33_1_fu_298_p1;
                trunc_ln33_1_reg_399_pp0_iter1_reg <= trunc_ln33_1_reg_399;
                trunc_ln33_3_reg_394 <= add_ln33_fu_282_p2(63 downto 3);
                trunc_ln33_reg_385 <= trunc_ln33_fu_256_p1;
                trunc_ln33_reg_385_pp0_iter1_reg <= trunc_ln33_reg_385;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                lshr_ln_reg_389_pp0_iter2_reg <= lshr_ln_reg_389_pp0_iter1_reg;
                lshr_ln_reg_389_pp0_iter3_reg <= lshr_ln_reg_389_pp0_iter2_reg;
                lshr_ln_reg_389_pp0_iter4_reg <= lshr_ln_reg_389_pp0_iter3_reg;
                lshr_ln_reg_389_pp0_iter5_reg <= lshr_ln_reg_389_pp0_iter4_reg;
                lshr_ln_reg_389_pp0_iter6_reg <= lshr_ln_reg_389_pp0_iter5_reg;
                lshr_ln_reg_389_pp0_iter7_reg <= lshr_ln_reg_389_pp0_iter6_reg;
                lshr_ln_reg_389_pp0_iter8_reg <= lshr_ln_reg_389_pp0_iter7_reg;
                lshr_ln_reg_389_pp0_iter9_reg <= lshr_ln_reg_389_pp0_iter8_reg;
                trunc_ln33_1_reg_399_pp0_iter2_reg <= trunc_ln33_1_reg_399_pp0_iter1_reg;
                trunc_ln33_1_reg_399_pp0_iter3_reg <= trunc_ln33_1_reg_399_pp0_iter2_reg;
                trunc_ln33_1_reg_399_pp0_iter4_reg <= trunc_ln33_1_reg_399_pp0_iter3_reg;
                trunc_ln33_1_reg_399_pp0_iter5_reg <= trunc_ln33_1_reg_399_pp0_iter4_reg;
                trunc_ln33_1_reg_399_pp0_iter6_reg <= trunc_ln33_1_reg_399_pp0_iter5_reg;
                trunc_ln33_1_reg_399_pp0_iter7_reg <= trunc_ln33_1_reg_399_pp0_iter6_reg;
                trunc_ln33_1_reg_399_pp0_iter8_reg <= trunc_ln33_1_reg_399_pp0_iter7_reg;
                trunc_ln33_1_reg_399_pp0_iter9_reg <= trunc_ln33_1_reg_399_pp0_iter8_reg;
                trunc_ln33_reg_385_pp0_iter2_reg <= trunc_ln33_reg_385_pp0_iter1_reg;
                trunc_ln33_reg_385_pp0_iter3_reg <= trunc_ln33_reg_385_pp0_iter2_reg;
                trunc_ln33_reg_385_pp0_iter4_reg <= trunc_ln33_reg_385_pp0_iter3_reg;
                trunc_ln33_reg_385_pp0_iter5_reg <= trunc_ln33_reg_385_pp0_iter4_reg;
                trunc_ln33_reg_385_pp0_iter6_reg <= trunc_ln33_reg_385_pp0_iter5_reg;
                trunc_ln33_reg_385_pp0_iter7_reg <= trunc_ln33_reg_385_pp0_iter6_reg;
                trunc_ln33_reg_385_pp0_iter8_reg <= trunc_ln33_reg_385_pp0_iter7_reg;
                trunc_ln33_reg_385_pp0_iter9_reg <= trunc_ln33_reg_385_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                gmem1_addr_read_reg_410 <= m_axi_gmem1_0_RDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln30_fu_250_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_oc_1) + unsigned(ap_const_lv8_1));
    add_ln33_fu_282_p2 <= std_logic_vector(unsigned(zext_ln33_1_fu_278_p1) + unsigned(bias));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, m_axi_gmem1_0_ARREADY, m_axi_gmem1_0_RVALID)
    begin
                ap_block_pp0_stage0_11001 <= (((m_axi_gmem1_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1)) or ((m_axi_gmem1_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, m_axi_gmem1_0_ARREADY, m_axi_gmem1_0_RVALID)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((m_axi_gmem1_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1)) or ((m_axi_gmem1_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, m_axi_gmem1_0_ARREADY, m_axi_gmem1_0_RVALID)
    begin
                ap_block_pp0_stage0_subdone <= (((m_axi_gmem1_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1)) or ((m_axi_gmem1_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln30_fu_244_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln30_fu_244_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter9_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_oc_1_assign_proc : process(ap_CS_fsm_pp0_stage0, oc_fu_104, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_oc_1 <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_oc_1 <= oc_fu_104;
        end if; 
    end process;


    gmem1_blk_n_AR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem1_0_ARREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            gmem1_blk_n_AR <= m_axi_gmem1_0_ARREADY;
        else 
            gmem1_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem1_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter9, m_axi_gmem1_0_RVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            gmem1_blk_n_R <= m_axi_gmem1_0_RVALID;
        else 
            gmem1_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln30_fu_244_p2 <= "1" when (ap_sig_allocacmp_oc_1 = out_ch) else "0";
    lshr_ln33_fu_357_p2 <= std_logic_vector(shift_right(unsigned(gmem1_addr_read_reg_410),to_integer(unsigned('0' & zext_ln33_2_fu_353_p1(31-1 downto 0)))));
    m_axi_gmem1_0_ARADDR <= sext_ln33_fu_325_p1;
    m_axi_gmem1_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem1_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem1_0_ARID <= ap_const_lv1_0;
    m_axi_gmem1_0_ARLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_gmem1_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem1_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem1_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem1_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem1_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem1_0_ARUSER <= ap_const_lv1_0;

    m_axi_gmem1_0_ARVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_gmem1_0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem1_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem1_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_0_AWID <= ap_const_lv1_0;
    m_axi_gmem1_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem1_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem1_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem1_0_BREADY <= ap_const_logic_0;

    m_axi_gmem1_0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_gmem1_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem1_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_0_WDATA <= ap_const_lv64_0;
    m_axi_gmem1_0_WID <= ap_const_lv1_0;
    m_axi_gmem1_0_WLAST <= ap_const_logic_0;
    m_axi_gmem1_0_WSTRB <= ap_const_lv8_0;
    m_axi_gmem1_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem1_0_WVALID <= ap_const_logic_0;
        sext_ln33_fu_325_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln33_3_reg_394),64));

    shl_ln33_1_fu_346_p3 <= (trunc_ln33_1_reg_399_pp0_iter9_reg & ap_const_lv3_0);
    shl_ln_fu_270_p3 <= (ap_sig_allocacmp_oc_1 & ap_const_lv2_0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_1_address0 <= zext_ln33_fu_335_p1(3 - 1 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_1_ce0 <= speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_1_ce0_local;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_1_ce0_local <= ap_const_logic_1;
        else 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_1_d0 <= trunc_ln33_2_fu_362_p1;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_1_we0 <= speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_1_we0_local;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln33_reg_385_pp0_iter9_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln33_reg_385_pp0_iter9_reg = ap_const_lv3_6) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_1_we0_local <= ap_const_logic_1;
        else 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_2_address0 <= zext_ln33_fu_335_p1(3 - 1 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_2_ce0 <= speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_2_ce0_local;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_2_ce0_local <= ap_const_logic_1;
        else 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_2_d0 <= trunc_ln33_2_fu_362_p1;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_2_we0 <= speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_2_we0_local;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln33_reg_385_pp0_iter9_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln33_reg_385_pp0_iter9_reg = ap_const_lv3_5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_2_we0_local <= ap_const_logic_1;
        else 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_3_address0 <= zext_ln33_fu_335_p1(3 - 1 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_3_ce0 <= speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_3_ce0_local;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_3_ce0_local <= ap_const_logic_1;
        else 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_3_d0 <= trunc_ln33_2_fu_362_p1;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_3_we0 <= speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_3_we0_local;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln33_reg_385_pp0_iter9_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln33_reg_385_pp0_iter9_reg = ap_const_lv3_4) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_3_we0_local <= ap_const_logic_1;
        else 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_4_address0 <= zext_ln33_fu_335_p1(3 - 1 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_4_ce0 <= speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_4_ce0_local;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_4_ce0_local <= ap_const_logic_1;
        else 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_4_d0 <= trunc_ln33_2_fu_362_p1;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_4_we0 <= speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_4_we0_local;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln33_reg_385_pp0_iter9_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln33_reg_385_pp0_iter9_reg = ap_const_lv3_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_4_we0_local <= ap_const_logic_1;
        else 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_5_address0 <= zext_ln33_fu_335_p1(3 - 1 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_5_ce0 <= speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_5_ce0_local;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_5_ce0_local <= ap_const_logic_1;
        else 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_5_d0 <= trunc_ln33_2_fu_362_p1;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_5_we0 <= speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_5_we0_local;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_5_we0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln33_reg_385_pp0_iter9_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln33_reg_385_pp0_iter9_reg = ap_const_lv3_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_5_we0_local <= ap_const_logic_1;
        else 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_6_address0 <= zext_ln33_fu_335_p1(3 - 1 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_6_ce0 <= speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_6_ce0_local;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_6_ce0_local <= ap_const_logic_1;
        else 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_6_d0 <= trunc_ln33_2_fu_362_p1;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_6_we0 <= speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_6_we0_local;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_6_we0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln33_reg_385_pp0_iter9_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln33_reg_385_pp0_iter9_reg = ap_const_lv3_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_6_we0_local <= ap_const_logic_1;
        else 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_7_address0 <= zext_ln33_fu_335_p1(3 - 1 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_7_ce0 <= speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_7_ce0_local;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_7_ce0_local <= ap_const_logic_1;
        else 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_7_d0 <= trunc_ln33_2_fu_362_p1;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_7_we0 <= speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_7_we0_local;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_7_we0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln33_reg_385_pp0_iter9_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln33_reg_385_pp0_iter9_reg = ap_const_lv3_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_7_we0_local <= ap_const_logic_1;
        else 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_address0 <= zext_ln33_fu_335_p1(3 - 1 downto 0);
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_ce0 <= speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_ce0_local;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_ce0_local <= ap_const_logic_1;
        else 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_d0 <= trunc_ln33_2_fu_362_p1;
    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_we0 <= speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_we0_local;

    speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_we0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln33_reg_385_pp0_iter9_reg, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln33_reg_385_pp0_iter9_reg = ap_const_lv3_7) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_we0_local <= ap_const_logic_1;
        else 
            speakable_cnn_top_ap_uint_const_ap_uint_const_ap_int_const_ap_uint_ap_uint_a_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln33_1_fu_298_p1 <= add_ln33_fu_282_p2(3 - 1 downto 0);
    trunc_ln33_2_fu_362_p1 <= lshr_ln33_fu_357_p2(32 - 1 downto 0);
    trunc_ln33_fu_256_p1 <= ap_sig_allocacmp_oc_1(3 - 1 downto 0);
    zext_ln33_1_fu_278_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_270_p3),64));
    zext_ln33_2_fu_353_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln33_1_fu_346_p3),64));
    zext_ln33_fu_335_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_reg_389_pp0_iter9_reg),64));
end behav;
