// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
(* DowngradeIPIdentifiedWarnings="yes" *) module speakable_cnn_top_p_ZZ17speakable_cnn_topPK7ap_uintILi64EES2_PK6ap_intILi32EEPS0_S_ILi8EES8_S8_cnw (
    address0, ce0,
    q0,
    address1, ce1,
    d1, we1,
    reset, clk);

parameter DataWidth = 8;
parameter AddressWidth = 5;
parameter AddressRange = 32;

input [AddressWidth-1:0] address0;
input ce0;
output reg [DataWidth-1:0] q0;
input [AddressWidth-1:0] address1;
input ce1;
input [DataWidth-1:0] d1;
input we1;
input reset;
input clk;

(* ram_style = "distributed" *) reg [DataWidth-1:0] ram[0:AddressRange-1];

initial begin
    $readmemh("./speakable_cnn_top_p_ZZ17speakable_cnn_topPK7ap_uintILi64EES2_PK6ap_intILi32EEPS0_S_ILi8EES8_S8_cnw.dat", ram);
end

always @(posedge clk)
begin
    if (ce0)
    begin
        q0 <= ram[address0];
    end
end

always @(posedge clk)
begin
    if (ce1)
    begin
        if (we1)
            ram[address1] <= d1;
    end
end


endmodule

