// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
(* DowngradeIPIdentifiedWarnings="yes" *) module speakable_cnn_top_p_ZZ17speakable_cnn_topPK7ap_uintILi64EES2_PK6ap_intILi32EEPS0_S_ILi8EES8_S8_bll (
    address0, ce0,
    d0, we0,
    q0,
    reset, clk);

parameter DataWidth = 8;
parameter AddressWidth = 10;
parameter AddressRange = 640;

input [AddressWidth-1:0] address0;
input ce0;
input [DataWidth-1:0] d0;
input we0;
output reg [DataWidth-1:0] q0;
input reset;
input clk;

(* ram_style = "auto" *) reg [DataWidth-1:0] ram[0:AddressRange-1];

initial begin
    $readmemh("./speakable_cnn_top_p_ZZ17speakable_cnn_topPK7ap_uintILi64EES2_PK6ap_intILi32EEPS0_S_ILi8EES8_S8_bll.dat", ram);
end

// read first
always @(posedge clk)
begin
    if (ce0)
    begin
        if (we0)
            ram[address0] <= d0;
        q0 <= ram[address0];
    end
end


endmodule

