// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1ns / 1ps

(* DowngradeIPIdentifiedWarnings="yes" *) module speakable_cnn_top_partselect_8ns_64ns_6ns_8_1_1 (sel,din,dout);

parameter ADDRWIDTH = 6;
parameter DATAWIDTH = 64;
parameter DATA1WIDTH = 8;


input [ADDRWIDTH-1:0] sel;
input [DATAWIDTH-1:0] din;
output [DATA1WIDTH-1:0] dout;

wire [DATAWIDTH+DATA1WIDTH-1:0] din_tmp;
wire [DATA1WIDTH-1:0] dout_tmp;




assign din_tmp = { 8'b00000000,din };

assign dout_tmp = din_tmp[sel+8-1 -: 8];




assign dout = dout_tmp;




endmodule
