// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module dpu_conv_top_dpu_conv_top_Pipeline_COPY_OC_COPY_H_COPY_W (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem2_0_AWVALID,
        m_axi_gmem2_0_AWREADY,
        m_axi_gmem2_0_AWADDR,
        m_axi_gmem2_0_AWID,
        m_axi_gmem2_0_AWLEN,
        m_axi_gmem2_0_AWSIZE,
        m_axi_gmem2_0_AWBURST,
        m_axi_gmem2_0_AWLOCK,
        m_axi_gmem2_0_AWCACHE,
        m_axi_gmem2_0_AWPROT,
        m_axi_gmem2_0_AWQOS,
        m_axi_gmem2_0_AWREGION,
        m_axi_gmem2_0_AWUSER,
        m_axi_gmem2_0_WVALID,
        m_axi_gmem2_0_WREADY,
        m_axi_gmem2_0_WDATA,
        m_axi_gmem2_0_WSTRB,
        m_axi_gmem2_0_WLAST,
        m_axi_gmem2_0_WID,
        m_axi_gmem2_0_WUSER,
        m_axi_gmem2_0_ARVALID,
        m_axi_gmem2_0_ARREADY,
        m_axi_gmem2_0_ARADDR,
        m_axi_gmem2_0_ARID,
        m_axi_gmem2_0_ARLEN,
        m_axi_gmem2_0_ARSIZE,
        m_axi_gmem2_0_ARBURST,
        m_axi_gmem2_0_ARLOCK,
        m_axi_gmem2_0_ARCACHE,
        m_axi_gmem2_0_ARPROT,
        m_axi_gmem2_0_ARQOS,
        m_axi_gmem2_0_ARREGION,
        m_axi_gmem2_0_ARUSER,
        m_axi_gmem2_0_RVALID,
        m_axi_gmem2_0_RREADY,
        m_axi_gmem2_0_RDATA,
        m_axi_gmem2_0_RLAST,
        m_axi_gmem2_0_RID,
        m_axi_gmem2_0_RFIFONUM,
        m_axi_gmem2_0_RUSER,
        m_axi_gmem2_0_RRESP,
        m_axi_gmem2_0_BVALID,
        m_axi_gmem2_0_BREADY,
        m_axi_gmem2_0_BRESP,
        m_axi_gmem2_0_BID,
        m_axi_gmem2_0_BUSER,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        ofmap,
        mul_ln112_1,
        in_w,
        zext_ln119,
        mul_ln112,
        conv_scratch
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem2_0_AWVALID;
input   m_axi_gmem2_0_AWREADY;
output  [63:0] m_axi_gmem2_0_AWADDR;
output  [0:0] m_axi_gmem2_0_AWID;
output  [31:0] m_axi_gmem2_0_AWLEN;
output  [2:0] m_axi_gmem2_0_AWSIZE;
output  [1:0] m_axi_gmem2_0_AWBURST;
output  [1:0] m_axi_gmem2_0_AWLOCK;
output  [3:0] m_axi_gmem2_0_AWCACHE;
output  [2:0] m_axi_gmem2_0_AWPROT;
output  [3:0] m_axi_gmem2_0_AWQOS;
output  [3:0] m_axi_gmem2_0_AWREGION;
output  [0:0] m_axi_gmem2_0_AWUSER;
output   m_axi_gmem2_0_WVALID;
input   m_axi_gmem2_0_WREADY;
output  [7:0] m_axi_gmem2_0_WDATA;
output  [0:0] m_axi_gmem2_0_WSTRB;
output   m_axi_gmem2_0_WLAST;
output  [0:0] m_axi_gmem2_0_WID;
output  [0:0] m_axi_gmem2_0_WUSER;
output   m_axi_gmem2_0_ARVALID;
input   m_axi_gmem2_0_ARREADY;
output  [63:0] m_axi_gmem2_0_ARADDR;
output  [0:0] m_axi_gmem2_0_ARID;
output  [31:0] m_axi_gmem2_0_ARLEN;
output  [2:0] m_axi_gmem2_0_ARSIZE;
output  [1:0] m_axi_gmem2_0_ARBURST;
output  [1:0] m_axi_gmem2_0_ARLOCK;
output  [3:0] m_axi_gmem2_0_ARCACHE;
output  [2:0] m_axi_gmem2_0_ARPROT;
output  [3:0] m_axi_gmem2_0_ARQOS;
output  [3:0] m_axi_gmem2_0_ARREGION;
output  [0:0] m_axi_gmem2_0_ARUSER;
input   m_axi_gmem2_0_RVALID;
output   m_axi_gmem2_0_RREADY;
input  [7:0] m_axi_gmem2_0_RDATA;
input   m_axi_gmem2_0_RLAST;
input  [0:0] m_axi_gmem2_0_RID;
input  [10:0] m_axi_gmem2_0_RFIFONUM;
input  [0:0] m_axi_gmem2_0_RUSER;
input  [1:0] m_axi_gmem2_0_RRESP;
input   m_axi_gmem2_0_BVALID;
output   m_axi_gmem2_0_BREADY;
input  [1:0] m_axi_gmem2_0_BRESP;
input  [0:0] m_axi_gmem2_0_BID;
input  [0:0] m_axi_gmem2_0_BUSER;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [7:0] m_axi_gmem0_0_WDATA;
output  [0:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [7:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [10:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
input  [63:0] ofmap;
input  [23:0] mul_ln112_1;
input  [7:0] in_w;
input  [7:0] zext_ln119;
input  [15:0] mul_ln112;
input  [63:0] conv_scratch;

reg ap_idle;
reg m_axi_gmem2_0_ARVALID;
reg m_axi_gmem2_0_RREADY;
reg m_axi_gmem0_0_AWVALID;
reg m_axi_gmem0_0_WVALID;
reg m_axi_gmem0_0_BREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_idle_pp0;
reg   [0:0] or_ln117_reg_616;
reg   [0:0] or_ln117_reg_616_pp0_iter3_reg;
reg    ap_block_state5_io_grp1;
reg   [0:0] icmp_ln119_2_reg_620;
reg   [0:0] icmp_ln119_2_reg_620_pp0_iter17_reg;
reg    ap_block_state19_pp0_stage0_iter18_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln115_fu_234_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_B;
wire    ap_block_pp0_stage0_grp1;
reg    gmem0_blk_n_W;
reg    gmem0_blk_n_AW;
reg    gmem2_blk_n_R;
reg    gmem2_blk_n_AR;
reg   [0:0] first_iter_2_reg_184;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln119_cast_fu_196_p1;
reg   [63:0] zext_ln119_cast_reg_590;
reg   [0:0] icmp_ln115_reg_596;
reg   [0:0] icmp_ln115_reg_596_pp0_iter2_reg;
wire   [0:0] icmp_ln117_fu_245_p2;
reg   [0:0] icmp_ln117_reg_600;
reg   [0:0] icmp_ln117_reg_600_pp0_iter2_reg;
wire   [0:0] select_ln115_4_fu_266_p3;
reg   [0:0] select_ln115_4_reg_609;
reg   [0:0] select_ln115_4_reg_609_pp0_iter2_reg;
wire   [0:0] or_ln117_fu_274_p2;
reg   [0:0] or_ln117_reg_616_pp0_iter2_reg;
wire   [0:0] icmp_ln119_2_fu_300_p2;
reg   [0:0] icmp_ln119_2_reg_620_pp0_iter2_reg;
reg   [0:0] icmp_ln119_2_reg_620_pp0_iter3_reg;
reg   [0:0] icmp_ln119_2_reg_620_pp0_iter4_reg;
reg   [0:0] icmp_ln119_2_reg_620_pp0_iter5_reg;
reg   [0:0] icmp_ln119_2_reg_620_pp0_iter6_reg;
reg   [0:0] icmp_ln119_2_reg_620_pp0_iter7_reg;
reg   [0:0] icmp_ln119_2_reg_620_pp0_iter8_reg;
reg   [0:0] icmp_ln119_2_reg_620_pp0_iter9_reg;
reg   [0:0] icmp_ln119_2_reg_620_pp0_iter10_reg;
reg   [0:0] icmp_ln119_2_reg_620_pp0_iter11_reg;
reg   [0:0] icmp_ln119_2_reg_620_pp0_iter12_reg;
reg   [0:0] icmp_ln119_2_reg_620_pp0_iter13_reg;
reg   [0:0] icmp_ln119_2_reg_620_pp0_iter14_reg;
reg   [0:0] icmp_ln119_2_reg_620_pp0_iter15_reg;
reg   [0:0] icmp_ln119_2_reg_620_pp0_iter16_reg;
reg   [7:0] oh_reg_624;
reg   [7:0] oc_reg_629;
wire   [7:0] add_ln115_1_fu_347_p2;
reg   [7:0] add_ln115_1_reg_634;
wire   [7:0] add_ln117_fu_360_p2;
reg   [7:0] add_ln117_reg_639;
reg   [63:0] gmem2_addr_reg_644;
reg   [63:0] gmem0_addr_reg_650;
reg   [7:0] gmem2_addr_read_reg_661;
reg    ap_condition_exit_pp0_iter3_stage0;
reg   [0:0] ap_phi_mux_first_iter_2_phi_fu_188_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
wire   [63:0] add_ln119_3_fu_502_p2;
wire   [63:0] select_ln117_1_fu_490_p3;
reg    ap_block_pp0_stage0_01001_grp1;
reg   [7:0] ow_fu_98;
wire   [7:0] select_ln119_fu_292_p3;
reg   [7:0] oh_1_fu_102;
wire   [7:0] select_ln117_2_fu_366_p3;
reg   [15:0] indvar_flatten35_fu_106;
wire   [15:0] select_ln117_3_fu_311_p3;
reg   [7:0] oc_1_fu_110;
wire   [7:0] select_ln115_5_fu_353_p3;
reg   [23:0] indvar_flatten57_fu_114;
wire   [23:0] add_ln115_fu_239_p2;
wire   [0:0] icmp_ln119_fu_256_p2;
wire   [0:0] icmp_ln119_1_fu_261_p2;
wire   [0:0] or_ln115_fu_250_p2;
wire   [0:0] or_ln119_fu_286_p2;
wire   [7:0] add_ln119_7_fu_280_p2;
wire   [15:0] add_ln117_1_fu_305_p2;
wire   [7:0] select_ln115_fu_340_p3;
wire   [19:0] shl_ln1_fu_383_p3;
wire   [13:0] shl_ln119_1_fu_394_p3;
wire   [63:0] zext_ln119_1_fu_401_p1;
wire   [63:0] add_ln119_fu_405_p2;
wire   [63:0] zext_ln117_fu_390_p1;
wire   [19:0] shl_ln119_mid1_fu_416_p3;
wire   [19:0] select_ln115_1_fu_427_p3;
wire   [63:0] zext_ln117_1_fu_423_p1;
wire   [63:0] add_ln119_4_fu_445_p2;
wire   [63:0] add_ln119_1_fu_410_p2;
wire   [13:0] shl_ln119_1_mid1_fu_457_p3;
wire   [13:0] select_ln115_2_fu_438_p3;
wire   [13:0] select_ln117_fu_468_p3;
wire   [63:0] zext_ln119_2_fu_464_p1;
wire   [63:0] add_ln119_5_fu_479_p2;
wire   [63:0] zext_ln115_fu_434_p1;
wire   [63:0] add_ln119_6_fu_484_p2;
wire   [63:0] select_ln115_3_fu_450_p3;
wire   [63:0] zext_ln119_3_fu_475_p1;
wire   [63:0] add_ln119_2_fu_497_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ow_fu_98 = 8'd0;
#0 oh_1_fu_102 = 8'd0;
#0 indvar_flatten35_fu_106 = 16'd0;
#0 oc_1_fu_110 = 8'd0;
#0 indvar_flatten57_fu_114 = 24'd0;
#0 ap_done_reg = 1'b0;
end

dpu_conv_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter17_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter3_stage0)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln115_reg_596 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        first_iter_2_reg_184 <= 1'd0;
    end else if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        first_iter_2_reg_184 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten35_fu_106 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln115_fu_234_p2 == 1'd0))) begin
            indvar_flatten35_fu_106 <= select_ln117_3_fu_311_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten57_fu_114 <= 24'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln115_fu_234_p2 == 1'd0))) begin
            indvar_flatten57_fu_114 <= add_ln115_fu_239_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            oc_1_fu_110 <= 8'd0;
        end else if (((icmp_ln115_reg_596 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            oc_1_fu_110 <= select_ln115_5_fu_353_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            oh_1_fu_102 <= 8'd0;
        end else if (((icmp_ln115_reg_596 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            oh_1_fu_102 <= select_ln117_2_fu_366_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ow_fu_98 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln115_fu_234_p2 == 1'd0))) begin
            ow_fu_98 <= select_ln119_fu_292_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        add_ln115_1_reg_634 <= add_ln115_1_fu_347_p2;
        add_ln117_reg_639 <= add_ln117_fu_360_p2;
        gmem0_addr_reg_650 <= select_ln117_1_fu_490_p3;
        gmem2_addr_read_reg_661 <= m_axi_gmem2_0_RDATA;
        gmem2_addr_reg_644 <= add_ln119_3_fu_502_p2;
        oc_reg_629 <= oc_1_fu_110;
        oh_reg_624 <= oh_1_fu_102;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln115_reg_596_pp0_iter2_reg <= icmp_ln115_reg_596;
        icmp_ln117_reg_600_pp0_iter2_reg <= icmp_ln117_reg_600;
        icmp_ln119_2_reg_620_pp0_iter10_reg <= icmp_ln119_2_reg_620_pp0_iter9_reg;
        icmp_ln119_2_reg_620_pp0_iter11_reg <= icmp_ln119_2_reg_620_pp0_iter10_reg;
        icmp_ln119_2_reg_620_pp0_iter12_reg <= icmp_ln119_2_reg_620_pp0_iter11_reg;
        icmp_ln119_2_reg_620_pp0_iter13_reg <= icmp_ln119_2_reg_620_pp0_iter12_reg;
        icmp_ln119_2_reg_620_pp0_iter14_reg <= icmp_ln119_2_reg_620_pp0_iter13_reg;
        icmp_ln119_2_reg_620_pp0_iter15_reg <= icmp_ln119_2_reg_620_pp0_iter14_reg;
        icmp_ln119_2_reg_620_pp0_iter16_reg <= icmp_ln119_2_reg_620_pp0_iter15_reg;
        icmp_ln119_2_reg_620_pp0_iter17_reg <= icmp_ln119_2_reg_620_pp0_iter16_reg;
        icmp_ln119_2_reg_620_pp0_iter2_reg <= icmp_ln119_2_reg_620;
        icmp_ln119_2_reg_620_pp0_iter3_reg <= icmp_ln119_2_reg_620_pp0_iter2_reg;
        icmp_ln119_2_reg_620_pp0_iter4_reg <= icmp_ln119_2_reg_620_pp0_iter3_reg;
        icmp_ln119_2_reg_620_pp0_iter5_reg <= icmp_ln119_2_reg_620_pp0_iter4_reg;
        icmp_ln119_2_reg_620_pp0_iter6_reg <= icmp_ln119_2_reg_620_pp0_iter5_reg;
        icmp_ln119_2_reg_620_pp0_iter7_reg <= icmp_ln119_2_reg_620_pp0_iter6_reg;
        icmp_ln119_2_reg_620_pp0_iter8_reg <= icmp_ln119_2_reg_620_pp0_iter7_reg;
        icmp_ln119_2_reg_620_pp0_iter9_reg <= icmp_ln119_2_reg_620_pp0_iter8_reg;
        or_ln117_reg_616_pp0_iter2_reg <= or_ln117_reg_616;
        or_ln117_reg_616_pp0_iter3_reg <= or_ln117_reg_616_pp0_iter2_reg;
        select_ln115_4_reg_609_pp0_iter2_reg <= select_ln115_4_reg_609;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln115_reg_596 <= icmp_ln115_fu_234_p2;
        icmp_ln117_reg_600 <= icmp_ln117_fu_245_p2;
        icmp_ln119_2_reg_620 <= icmp_ln119_2_fu_300_p2;
        or_ln117_reg_616 <= or_ln117_fu_274_p2;
        select_ln115_4_reg_609 <= select_ln115_4_fu_266_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln119_cast_reg_590[7 : 0] <= zext_ln119_cast_fu_196_p1[7 : 0];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln115_fu_234_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln115_reg_596_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter17_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln115_reg_596 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_first_iter_2_phi_fu_188_p4 = 1'd0;
    end else begin
        ap_phi_mux_first_iter_2_phi_fu_188_p4 = first_iter_2_reg_184;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (or_ln117_reg_616_pp0_iter3_reg == 1'd1))) begin
        gmem0_blk_n_AW = m_axi_gmem0_0_AWREADY;
    end else begin
        gmem0_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (icmp_ln119_2_reg_620_pp0_iter17_reg == 1'd1))) begin
        gmem0_blk_n_B = m_axi_gmem0_0_BVALID;
    end else begin
        gmem0_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem0_blk_n_W = m_axi_gmem0_0_WREADY;
    end else begin
        gmem0_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (or_ln117_reg_616_pp0_iter3_reg == 1'd1))) begin
        gmem2_blk_n_AR = m_axi_gmem2_0_ARREADY;
    end else begin
        gmem2_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem2_blk_n_R = m_axi_gmem2_0_RVALID;
    end else begin
        gmem2_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (or_ln117_reg_616_pp0_iter3_reg == 1'd1))) begin
        m_axi_gmem0_0_AWVALID = 1'b1;
    end else begin
        m_axi_gmem0_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln119_2_reg_620_pp0_iter17_reg == 1'd1))) begin
        m_axi_gmem0_0_BREADY = 1'b1;
    end else begin
        m_axi_gmem0_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem0_0_WVALID = 1'b1;
    end else begin
        m_axi_gmem0_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (or_ln117_reg_616_pp0_iter3_reg == 1'd1))) begin
        m_axi_gmem2_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem2_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem2_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem2_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln115_1_fu_347_p2 = (oc_1_fu_110 + 8'd1);

assign add_ln115_fu_239_p2 = (indvar_flatten57_fu_114 + 24'd1);

assign add_ln117_1_fu_305_p2 = (indvar_flatten35_fu_106 + 16'd1);

assign add_ln117_fu_360_p2 = (select_ln115_fu_340_p3 + 8'd1);

assign add_ln119_1_fu_410_p2 = (add_ln119_fu_405_p2 + zext_ln117_fu_390_p1);

assign add_ln119_2_fu_497_p2 = (zext_ln119_3_fu_475_p1 + conv_scratch);

assign add_ln119_3_fu_502_p2 = (add_ln119_2_fu_497_p2 + zext_ln115_fu_434_p1);

assign add_ln119_4_fu_445_p2 = (zext_ln117_1_fu_423_p1 + ofmap);

assign add_ln119_5_fu_479_p2 = (zext_ln119_2_fu_464_p1 + ofmap);

assign add_ln119_6_fu_484_p2 = (add_ln119_5_fu_479_p2 + zext_ln115_fu_434_p1);

assign add_ln119_7_fu_280_p2 = (ow_fu_98 + 8'd1);

assign add_ln119_fu_405_p2 = (zext_ln119_1_fu_401_p1 + ofmap);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_block_state19_pp0_stage0_iter18_grp1)) | ((ap_enable_reg_pp0_iter12 == 1'b1) & (m_axi_gmem2_0_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_block_state19_pp0_stage0_iter18_grp1)) | ((ap_enable_reg_pp0_iter13 == 1'b1) & (m_axi_gmem0_0_WREADY == 1'b0)) | ((ap_enable_reg_pp0_iter12 == 1'b1) & (m_axi_gmem2_0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_io_grp1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_block_state19_pp0_stage0_iter18_grp1)) | ((ap_enable_reg_pp0_iter13 == 1'b1) & (m_axi_gmem0_0_WREADY == 1'b0)) | ((ap_enable_reg_pp0_iter12 == 1'b1) & (m_axi_gmem2_0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_io_grp1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_block_state19_pp0_stage0_iter18_grp1)) | ((ap_enable_reg_pp0_iter13 == 1'b1) & (m_axi_gmem0_0_WREADY == 1'b0)) | ((ap_enable_reg_pp0_iter12 == 1'b1) & (m_axi_gmem2_0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_io_grp1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state19_pp0_stage0_iter18_grp1 = ((icmp_ln119_2_reg_620_pp0_iter17_reg == 1'd1) & (m_axi_gmem0_0_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state5_io_grp1 = (((or_ln117_reg_616_pp0_iter3_reg == 1'd1) & (m_axi_gmem0_0_AWREADY == 1'b0)) | ((or_ln117_reg_616_pp0_iter3_reg == 1'd1) & (m_axi_gmem2_0_ARREADY == 1'b0)));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln115_fu_234_p2 = ((indvar_flatten57_fu_114 == mul_ln112_1) ? 1'b1 : 1'b0);

assign icmp_ln117_fu_245_p2 = ((indvar_flatten35_fu_106 == mul_ln112) ? 1'b1 : 1'b0);

assign icmp_ln119_1_fu_261_p2 = ((ow_fu_98 == in_w) ? 1'b1 : 1'b0);

assign icmp_ln119_2_fu_300_p2 = ((select_ln119_fu_292_p3 == in_w) ? 1'b1 : 1'b0);

assign icmp_ln119_fu_256_p2 = ((in_w == 8'd0) ? 1'b1 : 1'b0);

assign m_axi_gmem0_0_ARADDR = 64'd0;

assign m_axi_gmem0_0_ARBURST = 2'd0;

assign m_axi_gmem0_0_ARCACHE = 4'd0;

assign m_axi_gmem0_0_ARID = 1'd0;

assign m_axi_gmem0_0_ARLEN = 32'd0;

assign m_axi_gmem0_0_ARLOCK = 2'd0;

assign m_axi_gmem0_0_ARPROT = 3'd0;

assign m_axi_gmem0_0_ARQOS = 4'd0;

assign m_axi_gmem0_0_ARREGION = 4'd0;

assign m_axi_gmem0_0_ARSIZE = 3'd0;

assign m_axi_gmem0_0_ARUSER = 1'd0;

assign m_axi_gmem0_0_ARVALID = 1'b0;

assign m_axi_gmem0_0_AWADDR = gmem0_addr_reg_650;

assign m_axi_gmem0_0_AWBURST = 2'd0;

assign m_axi_gmem0_0_AWCACHE = 4'd0;

assign m_axi_gmem0_0_AWID = 1'd0;

assign m_axi_gmem0_0_AWLEN = zext_ln119_cast_reg_590;

assign m_axi_gmem0_0_AWLOCK = 2'd0;

assign m_axi_gmem0_0_AWPROT = 3'd0;

assign m_axi_gmem0_0_AWQOS = 4'd0;

assign m_axi_gmem0_0_AWREGION = 4'd0;

assign m_axi_gmem0_0_AWSIZE = 3'd0;

assign m_axi_gmem0_0_AWUSER = 1'd0;

assign m_axi_gmem0_0_RREADY = 1'b0;

assign m_axi_gmem0_0_WDATA = gmem2_addr_read_reg_661;

assign m_axi_gmem0_0_WID = 1'd0;

assign m_axi_gmem0_0_WLAST = 1'b0;

assign m_axi_gmem0_0_WSTRB = 1'd1;

assign m_axi_gmem0_0_WUSER = 1'd0;

assign m_axi_gmem2_0_ARADDR = gmem2_addr_reg_644;

assign m_axi_gmem2_0_ARBURST = 2'd0;

assign m_axi_gmem2_0_ARCACHE = 4'd0;

assign m_axi_gmem2_0_ARID = 1'd0;

assign m_axi_gmem2_0_ARLEN = zext_ln119_cast_reg_590;

assign m_axi_gmem2_0_ARLOCK = 2'd0;

assign m_axi_gmem2_0_ARPROT = 3'd0;

assign m_axi_gmem2_0_ARQOS = 4'd0;

assign m_axi_gmem2_0_ARREGION = 4'd0;

assign m_axi_gmem2_0_ARSIZE = 3'd0;

assign m_axi_gmem2_0_ARUSER = 1'd0;

assign m_axi_gmem2_0_AWADDR = 64'd0;

assign m_axi_gmem2_0_AWBURST = 2'd0;

assign m_axi_gmem2_0_AWCACHE = 4'd0;

assign m_axi_gmem2_0_AWID = 1'd0;

assign m_axi_gmem2_0_AWLEN = 32'd0;

assign m_axi_gmem2_0_AWLOCK = 2'd0;

assign m_axi_gmem2_0_AWPROT = 3'd0;

assign m_axi_gmem2_0_AWQOS = 4'd0;

assign m_axi_gmem2_0_AWREGION = 4'd0;

assign m_axi_gmem2_0_AWSIZE = 3'd0;

assign m_axi_gmem2_0_AWUSER = 1'd0;

assign m_axi_gmem2_0_AWVALID = 1'b0;

assign m_axi_gmem2_0_BREADY = 1'b0;

assign m_axi_gmem2_0_WDATA = 8'd0;

assign m_axi_gmem2_0_WID = 1'd0;

assign m_axi_gmem2_0_WLAST = 1'b0;

assign m_axi_gmem2_0_WSTRB = 1'd0;

assign m_axi_gmem2_0_WUSER = 1'd0;

assign m_axi_gmem2_0_WVALID = 1'b0;

assign or_ln115_fu_250_p2 = (icmp_ln117_fu_245_p2 | ap_phi_mux_first_iter_2_phi_fu_188_p4);

assign or_ln117_fu_274_p2 = (select_ln115_4_fu_266_p3 | or_ln115_fu_250_p2);

assign or_ln119_fu_286_p2 = (select_ln115_4_fu_266_p3 | icmp_ln117_fu_245_p2);

assign select_ln115_1_fu_427_p3 = ((icmp_ln117_reg_600_pp0_iter2_reg[0:0] == 1'b1) ? shl_ln119_mid1_fu_416_p3 : shl_ln1_fu_383_p3);

assign select_ln115_2_fu_438_p3 = ((icmp_ln117_reg_600_pp0_iter2_reg[0:0] == 1'b1) ? 14'd0 : shl_ln119_1_fu_394_p3);

assign select_ln115_3_fu_450_p3 = ((icmp_ln117_reg_600_pp0_iter2_reg[0:0] == 1'b1) ? add_ln119_4_fu_445_p2 : add_ln119_1_fu_410_p2);

assign select_ln115_4_fu_266_p3 = ((icmp_ln117_fu_245_p2[0:0] == 1'b1) ? icmp_ln119_fu_256_p2 : icmp_ln119_1_fu_261_p2);

assign select_ln115_5_fu_353_p3 = ((icmp_ln117_reg_600[0:0] == 1'b1) ? add_ln115_1_fu_347_p2 : oc_1_fu_110);

assign select_ln115_fu_340_p3 = ((icmp_ln117_reg_600[0:0] == 1'b1) ? 8'd0 : oh_1_fu_102);

assign select_ln117_1_fu_490_p3 = ((select_ln115_4_reg_609_pp0_iter2_reg[0:0] == 1'b1) ? add_ln119_6_fu_484_p2 : select_ln115_3_fu_450_p3);

assign select_ln117_2_fu_366_p3 = ((select_ln115_4_reg_609[0:0] == 1'b1) ? add_ln117_fu_360_p2 : select_ln115_fu_340_p3);

assign select_ln117_3_fu_311_p3 = ((icmp_ln117_fu_245_p2[0:0] == 1'b1) ? 16'd1 : add_ln117_1_fu_305_p2);

assign select_ln117_fu_468_p3 = ((select_ln115_4_reg_609_pp0_iter2_reg[0:0] == 1'b1) ? shl_ln119_1_mid1_fu_457_p3 : select_ln115_2_fu_438_p3);

assign select_ln119_fu_292_p3 = ((or_ln119_fu_286_p2[0:0] == 1'b1) ? 8'd1 : add_ln119_7_fu_280_p2);

assign shl_ln119_1_fu_394_p3 = {{oh_reg_624}, {6'd0}};

assign shl_ln119_1_mid1_fu_457_p3 = {{add_ln117_reg_639}, {6'd0}};

assign shl_ln119_mid1_fu_416_p3 = {{add_ln115_1_reg_634}, {12'd0}};

assign shl_ln1_fu_383_p3 = {{oc_reg_629}, {12'd0}};

assign zext_ln115_fu_434_p1 = select_ln115_1_fu_427_p3;

assign zext_ln117_1_fu_423_p1 = shl_ln119_mid1_fu_416_p3;

assign zext_ln117_fu_390_p1 = shl_ln1_fu_383_p3;

assign zext_ln119_1_fu_401_p1 = shl_ln119_1_fu_394_p3;

assign zext_ln119_2_fu_464_p1 = shl_ln119_1_mid1_fu_457_p3;

assign zext_ln119_3_fu_475_p1 = select_ln117_fu_468_p3;

assign zext_ln119_cast_fu_196_p1 = zext_ln119;

always @ (posedge ap_clk) begin
    zext_ln119_cast_reg_590[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
end

endmodule //dpu_conv_top_dpu_conv_top_Pipeline_COPY_OC_COPY_H_COPY_W
