// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module dpu_conv_top_dpu_conv_top_Pipeline_POOL_OC_POOL_H_POOL_W (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem2_0_AWVALID,
        m_axi_gmem2_0_AWREADY,
        m_axi_gmem2_0_AWADDR,
        m_axi_gmem2_0_AWID,
        m_axi_gmem2_0_AWLEN,
        m_axi_gmem2_0_AWSIZE,
        m_axi_gmem2_0_AWBURST,
        m_axi_gmem2_0_AWLOCK,
        m_axi_gmem2_0_AWCACHE,
        m_axi_gmem2_0_AWPROT,
        m_axi_gmem2_0_AWQOS,
        m_axi_gmem2_0_AWREGION,
        m_axi_gmem2_0_AWUSER,
        m_axi_gmem2_0_WVALID,
        m_axi_gmem2_0_WREADY,
        m_axi_gmem2_0_WDATA,
        m_axi_gmem2_0_WSTRB,
        m_axi_gmem2_0_WLAST,
        m_axi_gmem2_0_WID,
        m_axi_gmem2_0_WUSER,
        m_axi_gmem2_0_ARVALID,
        m_axi_gmem2_0_ARREADY,
        m_axi_gmem2_0_ARADDR,
        m_axi_gmem2_0_ARID,
        m_axi_gmem2_0_ARLEN,
        m_axi_gmem2_0_ARSIZE,
        m_axi_gmem2_0_ARBURST,
        m_axi_gmem2_0_ARLOCK,
        m_axi_gmem2_0_ARCACHE,
        m_axi_gmem2_0_ARPROT,
        m_axi_gmem2_0_ARQOS,
        m_axi_gmem2_0_ARREGION,
        m_axi_gmem2_0_ARUSER,
        m_axi_gmem2_0_RVALID,
        m_axi_gmem2_0_RREADY,
        m_axi_gmem2_0_RDATA,
        m_axi_gmem2_0_RLAST,
        m_axi_gmem2_0_RID,
        m_axi_gmem2_0_RFIFONUM,
        m_axi_gmem2_0_RUSER,
        m_axi_gmem2_0_RRESP,
        m_axi_gmem2_0_BVALID,
        m_axi_gmem2_0_BREADY,
        m_axi_gmem2_0_BRESP,
        m_axi_gmem2_0_BID,
        m_axi_gmem2_0_BUSER,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        ofmap,
        mul_ln82_1,
        conv_scratch,
        lshr_ln1,
        zext_ln85,
        mul_ln82
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem2_0_AWVALID;
input   m_axi_gmem2_0_AWREADY;
output  [63:0] m_axi_gmem2_0_AWADDR;
output  [0:0] m_axi_gmem2_0_AWID;
output  [31:0] m_axi_gmem2_0_AWLEN;
output  [2:0] m_axi_gmem2_0_AWSIZE;
output  [1:0] m_axi_gmem2_0_AWBURST;
output  [1:0] m_axi_gmem2_0_AWLOCK;
output  [3:0] m_axi_gmem2_0_AWCACHE;
output  [2:0] m_axi_gmem2_0_AWPROT;
output  [3:0] m_axi_gmem2_0_AWQOS;
output  [3:0] m_axi_gmem2_0_AWREGION;
output  [0:0] m_axi_gmem2_0_AWUSER;
output   m_axi_gmem2_0_WVALID;
input   m_axi_gmem2_0_WREADY;
output  [7:0] m_axi_gmem2_0_WDATA;
output  [0:0] m_axi_gmem2_0_WSTRB;
output   m_axi_gmem2_0_WLAST;
output  [0:0] m_axi_gmem2_0_WID;
output  [0:0] m_axi_gmem2_0_WUSER;
output   m_axi_gmem2_0_ARVALID;
input   m_axi_gmem2_0_ARREADY;
output  [63:0] m_axi_gmem2_0_ARADDR;
output  [0:0] m_axi_gmem2_0_ARID;
output  [31:0] m_axi_gmem2_0_ARLEN;
output  [2:0] m_axi_gmem2_0_ARSIZE;
output  [1:0] m_axi_gmem2_0_ARBURST;
output  [1:0] m_axi_gmem2_0_ARLOCK;
output  [3:0] m_axi_gmem2_0_ARCACHE;
output  [2:0] m_axi_gmem2_0_ARPROT;
output  [3:0] m_axi_gmem2_0_ARQOS;
output  [3:0] m_axi_gmem2_0_ARREGION;
output  [0:0] m_axi_gmem2_0_ARUSER;
input   m_axi_gmem2_0_RVALID;
output   m_axi_gmem2_0_RREADY;
input  [7:0] m_axi_gmem2_0_RDATA;
input   m_axi_gmem2_0_RLAST;
input  [0:0] m_axi_gmem2_0_RID;
input  [10:0] m_axi_gmem2_0_RFIFONUM;
input  [0:0] m_axi_gmem2_0_RUSER;
input  [1:0] m_axi_gmem2_0_RRESP;
input   m_axi_gmem2_0_BVALID;
output   m_axi_gmem2_0_BREADY;
input  [1:0] m_axi_gmem2_0_BRESP;
input  [0:0] m_axi_gmem2_0_BID;
input  [0:0] m_axi_gmem2_0_BUSER;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [7:0] m_axi_gmem0_0_WDATA;
output  [0:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [7:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [10:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
input  [63:0] ofmap;
input  [21:0] mul_ln82_1;
input  [63:0] conv_scratch;
input  [6:0] lshr_ln1;
input  [6:0] zext_ln85;
input  [13:0] mul_ln82;

reg ap_idle;
reg m_axi_gmem2_0_ARVALID;
reg[63:0] m_axi_gmem2_0_ARADDR;
reg m_axi_gmem2_0_RREADY;
reg m_axi_gmem0_0_AWVALID;
reg m_axi_gmem0_0_WVALID;
reg m_axi_gmem0_0_BREADY;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
reg   [0:0] icmp_ln85_reg_678;
reg   [0:0] first_iter_0_reg_720;
reg    ap_predicate_op113_writereq_state4;
reg    ap_block_state4_io_grp1;
reg    ap_block_pp0_stage3_subdone_grp1_done_reg;
reg    ap_block_pp0_stage3_subdone_grp1;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_state4_io_grp2;
reg    ap_block_pp0_stage3_subdone_grp2_done_reg;
reg    ap_block_pp0_stage3_subdone_grp2;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage3_subdone_grp4_done_reg;
reg    ap_block_pp0_stage3_subdone_grp4;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_B;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp9;
reg   [0:0] icmp_ln89_2_reg_753;
reg   [0:0] icmp_ln89_2_reg_753_pp0_iter4_reg;
reg    ap_block_pp0_stage1_subdone_grp9_done_reg;
reg    ap_block_pp0_stage1_subdone_grp9;
reg    ap_block_pp0_stage1_subdone;
reg    gmem0_blk_n_W;
wire    ap_block_pp0_stage0_grp8;
reg    ap_block_pp0_stage0_subdone_grp8_done_reg;
reg    ap_block_pp0_stage0_subdone_grp8;
reg    ap_block_pp0_stage0_subdone;
reg    gmem0_blk_n_AW;
wire    ap_block_pp0_stage3_grp1;
reg    gmem2_blk_n_AR;
wire    ap_block_pp0_stage3_grp2;
reg    gmem2_blk_n_R;
wire    ap_block_pp0_stage3_grp4;
wire    ap_block_pp0_stage0_grp5;
reg    ap_block_pp0_stage0_subdone_grp5_done_reg;
reg    ap_block_pp0_stage0_subdone_grp5;
wire    ap_block_pp0_stage1_grp3;
reg    ap_block_pp0_stage1_subdone_grp3_done_reg;
reg    ap_block_pp0_stage1_subdone_grp3;
wire    ap_block_pp0_stage1_grp6;
reg    ap_block_pp0_stage1_subdone_grp6_done_reg;
reg    ap_block_pp0_stage1_subdone_grp6;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_grp7;
reg   [7:0] reg_195;
reg    ap_block_pp0_stage3_11001_grp4;
reg    ap_block_pp0_stage2_11001_grp7;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
wire   [63:0] zext_ln85_cast_fu_199_p1;
reg   [63:0] zext_ln85_cast_reg_663;
reg   [6:0] oh_1_reg_668;
reg    ap_block_state22_pp0_stage1_iter5_grp9;
reg    ap_block_pp0_stage1_11001;
wire   [19:0] shl_ln_fu_240_p3;
reg   [19:0] shl_ln_reg_673;
wire   [0:0] icmp_ln85_fu_248_p2;
reg   [0:0] icmp_ln85_reg_678_pp0_iter1_reg;
reg   [0:0] icmp_ln85_reg_678_pp0_iter2_reg;
reg   [0:0] icmp_ln85_reg_678_pp0_iter3_reg;
wire   [0:0] icmp_ln87_fu_262_p2;
reg   [0:0] icmp_ln87_reg_682;
wire   [6:0] select_ln85_fu_267_p3;
reg   [6:0] select_ln85_reg_687;
wire   [19:0] shl_ln91_mid1_fu_281_p3;
reg   [19:0] shl_ln91_mid1_reg_692;
wire   [63:0] zext_ln85_1_fu_297_p1;
reg   [63:0] zext_ln85_1_reg_697;
wire   [0:0] select_ln85_3_fu_311_p3;
reg   [0:0] select_ln85_3_reg_702;
wire   [6:0] add_ln87_fu_327_p2;
reg   [6:0] add_ln87_reg_708;
wire   [6:0] ow_mid2_fu_339_p3;
reg   [6:0] ow_mid2_reg_714;
wire   [0:0] first_iter_0_fu_347_p2;
wire   [63:0] add_ln91_fu_353_p2;
reg   [63:0] add_ln91_reg_724;
reg   [63:0] gmem0_addr_reg_730;
wire    ap_block_pp0_stage2_11001_grp0;
reg    ap_block_pp0_stage2_subdone_grp0_done_reg;
wire    ap_block_pp0_stage2_subdone_grp0;
reg    ap_block_pp0_stage2_subdone;
reg   [63:0] gmem2_addr_reg_735;
reg   [63:0] gmem2_addr_1_reg_741;
wire   [0:0] icmp_ln89_2_fu_548_p2;
reg   [0:0] icmp_ln89_2_reg_753_pp0_iter1_reg;
reg   [0:0] icmp_ln89_2_reg_753_pp0_iter2_reg;
reg   [0:0] icmp_ln89_2_reg_753_pp0_iter3_reg;
reg   [7:0] p01_reg_757;
reg    ap_block_pp0_stage0_11001_grp5;
reg   [7:0] p10_reg_763;
reg    ap_block_pp0_stage1_11001_grp6;
wire   [7:0] m0_fu_568_p3;
reg   [7:0] m0_reg_769;
wire   [7:0] select_ln98_fu_592_p3;
reg   [7:0] select_ln98_reg_775;
wire    ap_block_pp0_stage3_11001_grp0;
reg    ap_block_pp0_stage3_subdone_grp0_done_reg;
wire    ap_block_pp0_stage3_subdone_grp0;
wire   [63:0] add_ln91_2_mid2_fu_448_p3;
wire    ap_block_pp0_stage2_grp0;
wire   [63:0] add_ln91_7_fu_519_p2;
wire   [63:0] add_ln91_5_fu_508_p2;
reg    ap_block_pp0_stage3_11001_grp1;
reg    ap_block_pp0_stage3_11001_grp2;
reg    ap_block_pp0_stage1_11001_grp3;
reg    ap_block_pp0_stage0_11001_grp8;
wire    ap_block_pp0_stage0_01001_grp8;
reg    ap_block_pp0_stage1_11001_grp9;
reg   [6:0] ow_fu_108;
wire   [6:0] add_ln89_fu_543_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage1;
reg   [6:0] oh_fu_112;
wire   [6:0] select_ln87_fu_455_p3;
reg   [13:0] indvar_flatten_fu_116;
wire   [13:0] select_ln87_1_fu_364_p3;
reg   [7:0] oc_fu_120;
wire   [7:0] select_ln85_4_fu_319_p3;
reg   [21:0] indvar_flatten25_fu_124;
wire   [21:0] add_ln85_fu_253_p2;
wire    ap_block_pp0_stage0_grp0;
wire   [7:0] add_ln85_1_fu_275_p2;
wire   [19:0] select_ln85_1_fu_289_p3;
wire   [0:0] icmp_ln89_fu_301_p2;
wire   [0:0] icmp_ln89_1_fu_306_p2;
wire   [0:0] empty_67_fu_333_p2;
wire   [13:0] add_ln87_1_fu_358_p2;
wire   [12:0] shl_ln91_3_fu_390_p3;
wire   [63:0] zext_ln91_1_fu_397_p1;
wire   [63:0] add_ln91_1_fu_401_p2;
wire   [63:0] zext_ln91_fu_387_p1;
wire   [63:0] zext_ln91_5_fu_412_p1;
wire   [63:0] add_ln91_8_fu_415_p2;
wire   [63:0] add_ln91_2_fu_406_p2;
wire   [12:0] shl_ln91_3_mid1_fu_427_p3;
wire   [63:0] zext_ln91_6_fu_434_p1;
wire   [63:0] add_ln91_9_fu_438_p2;
wire   [63:0] add_ln91_10_fu_443_p2;
wire   [63:0] select_ln85_2_fu_420_p3;
wire   [13:0] shl_ln91_1_fu_466_p3;
wire   [7:0] shl_ln91_2_fu_478_p3;
wire   [63:0] zext_ln89_fu_474_p1;
wire   [8:0] zext_ln91_3_fu_489_p1;
wire   [8:0] add_ln91_4_fu_498_p2;
wire   [63:0] zext_ln91_4_fu_504_p1;
wire   [63:0] add_ln91_3_fu_493_p2;
wire   [63:0] zext_ln91_2_fu_485_p1;
wire   [63:0] add_ln91_6_fu_514_p2;
wire   [0:0] icmp_ln96_fu_563_p2;
wire    ap_block_pp0_stage3_grp0;
wire   [0:0] icmp_ln97_fu_575_p2;
wire   [7:0] m1_fu_580_p3;
wire   [0:0] icmp_ln98_fu_587_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage3_11001;
reg    ap_condition_exit_pp0_iter4_stage1;
reg    ap_idle_pp0_0to3;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [3:0] ap_NS_fsm;
reg    ap_done_pending_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp2_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp4_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp9_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp8_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp5_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp3_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp6_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp0_done_reg = 1'b0;
#0 ow_fu_108 = 7'd0;
#0 oh_fu_112 = 7'd0;
#0 indvar_flatten_fu_116 = 14'd0;
#0 oc_fu_120 = 8'd0;
#0 indvar_flatten25_fu_124 = 22'd0;
#0 ap_done_reg = 1'b0;
end

dpu_conv_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp5_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp5_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp5)) begin
                ap_block_pp0_stage0_subdone_grp5_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp8_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp8_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp8)) begin
                ap_block_pp0_stage0_subdone_grp8_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp3_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp3_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp3)) begin
                ap_block_pp0_stage1_subdone_grp3_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp6_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp6_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp6)) begin
                ap_block_pp0_stage1_subdone_grp6_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp9_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp9_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp9)) begin
                ap_block_pp0_stage1_subdone_grp9_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp0)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp0)) begin
                ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp1_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp1)) begin
                ap_block_pp0_stage3_subdone_grp1_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp2_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp2)) begin
                ap_block_pp0_stage3_subdone_grp2_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp4_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp4_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp4)) begin
                ap_block_pp0_stage3_subdone_grp4_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        indvar_flatten25_fu_124 <= 22'd0;
    end else if (((icmp_ln85_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        indvar_flatten25_fu_124 <= add_ln85_fu_253_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        indvar_flatten_fu_116 <= 14'd0;
    end else if (((icmp_ln85_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        indvar_flatten_fu_116 <= select_ln87_1_fu_364_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        oc_fu_120 <= 8'd0;
    end else if (((icmp_ln85_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        oc_fu_120 <= select_ln85_4_fu_319_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        oh_fu_112 <= 7'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp7) & (icmp_ln85_reg_678 == 1'd0))) begin
        oh_fu_112 <= select_ln87_fu_455_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        ow_fu_108 <= 7'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (icmp_ln85_reg_678 == 1'd0))) begin
        ow_fu_108 <= add_ln89_fu_543_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        add_ln87_reg_708 <= add_ln87_fu_327_p2;
        add_ln91_reg_724 <= add_ln91_fu_353_p2;
        first_iter_0_reg_720 <= first_iter_0_fu_347_p2;
        icmp_ln85_reg_678 <= icmp_ln85_fu_248_p2;
        icmp_ln85_reg_678_pp0_iter1_reg <= icmp_ln85_reg_678;
        icmp_ln85_reg_678_pp0_iter2_reg <= icmp_ln85_reg_678_pp0_iter1_reg;
        icmp_ln85_reg_678_pp0_iter3_reg <= icmp_ln85_reg_678_pp0_iter2_reg;
        icmp_ln87_reg_682 <= icmp_ln87_fu_262_p2;
        oh_1_reg_668 <= oh_fu_112;
        ow_mid2_reg_714 <= ow_mid2_fu_339_p3;
        select_ln85_3_reg_702 <= select_ln85_3_fu_311_p3;
        select_ln85_reg_687 <= select_ln85_fu_267_p3;
        shl_ln91_mid1_reg_692[19 : 12] <= shl_ln91_mid1_fu_281_p3[19 : 12];
        shl_ln_reg_673[19 : 12] <= shl_ln_fu_240_p3[19 : 12];
        zext_ln85_1_reg_697[19 : 12] <= zext_ln85_1_fu_297_p1[19 : 12];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        gmem0_addr_reg_730 <= add_ln91_2_mid2_fu_448_p3;
        icmp_ln89_2_reg_753 <= icmp_ln89_2_fu_548_p2;
        icmp_ln89_2_reg_753_pp0_iter1_reg <= icmp_ln89_2_reg_753;
        icmp_ln89_2_reg_753_pp0_iter2_reg <= icmp_ln89_2_reg_753_pp0_iter1_reg;
        icmp_ln89_2_reg_753_pp0_iter3_reg <= icmp_ln89_2_reg_753_pp0_iter2_reg;
        icmp_ln89_2_reg_753_pp0_iter4_reg <= icmp_ln89_2_reg_753_pp0_iter3_reg;
        m0_reg_769 <= m0_fu_568_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp7))) begin
        gmem2_addr_1_reg_741 <= add_ln91_5_fu_508_p2;
        gmem2_addr_reg_735 <= add_ln91_7_fu_519_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp5) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg))) begin
        p01_reg_757 <= m_axi_gmem2_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp6) & (1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg))) begin
        p10_reg_763 <= m_axi_gmem2_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp7)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001_grp4) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg)))) begin
        reg_195 <= m_axi_gmem2_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0))) begin
        select_ln98_reg_775 <= select_ln98_fu_592_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        zext_ln85_cast_reg_663[6 : 0] <= zext_ln85_cast_fu_199_p1[6 : 0];
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (icmp_ln85_reg_678 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln85_reg_678_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_condition_exit_pp0_iter4_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter4_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready_pp0_iter4_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (ap_loop_exit_ready == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to3 = 1'b1;
    end else begin
        ap_idle_pp0_0to3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_grp1) & (1'b0 == ap_block_pp0_stage3_subdone_grp1_done_reg) & (ap_predicate_op113_writereq_state4 == 1'b1))) begin
        gmem0_blk_n_AW = m_axi_gmem0_0_AWREADY;
    end else begin
        gmem0_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln89_2_reg_753_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp9_done_reg) & (1'b0 == ap_block_pp0_stage1_grp9))) begin
        gmem0_blk_n_B = m_axi_gmem0_0_BVALID;
    end else begin
        gmem0_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg) & (1'b0 == ap_block_pp0_stage0_grp8))) begin
        gmem0_blk_n_W = m_axi_gmem0_0_WREADY;
    end else begin
        gmem0_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_grp2) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg) & (icmp_ln85_reg_678 == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg) & (1'b0 == ap_block_pp0_stage1_grp3)))) begin
        gmem2_blk_n_AR = m_axi_gmem2_0_ARREADY;
    end else begin
        gmem2_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_grp7)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg) & (1'b0 == ap_block_pp0_stage1_grp6)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg) & (1'b0 == ap_block_pp0_stage0_grp5)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_grp4) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg)))) begin
        gmem2_blk_n_R = m_axi_gmem2_0_RVALID;
    end else begin
        gmem2_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp1) & (1'b0 == ap_block_pp0_stage3_subdone_grp1_done_reg) & (ap_predicate_op113_writereq_state4 == 1'b1))) begin
        m_axi_gmem0_0_AWVALID = 1'b1;
    end else begin
        m_axi_gmem0_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln89_2_reg_753_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp9) & (1'b0 == ap_block_pp0_stage1_subdone_grp9_done_reg))) begin
        m_axi_gmem0_0_BREADY = 1'b1;
    end else begin
        m_axi_gmem0_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp8) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg))) begin
        m_axi_gmem0_0_WVALID = 1'b1;
    end else begin
        m_axi_gmem0_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp3) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg))) begin
        m_axi_gmem2_0_ARADDR = gmem2_addr_1_reg_741;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp2) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg) & (icmp_ln85_reg_678 == 1'd0))) begin
        m_axi_gmem2_0_ARADDR = gmem2_addr_reg_735;
    end else begin
        m_axi_gmem2_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp2) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg) & (icmp_ln85_reg_678 == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp3) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg)))) begin
        m_axi_gmem2_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem2_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp7)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp6) & (1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp5) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001_grp4) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg)))) begin
        m_axi_gmem2_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem2_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln85_1_fu_275_p2 = (oc_fu_120 + 8'd1);

assign add_ln85_fu_253_p2 = (indvar_flatten25_fu_124 + 22'd1);

assign add_ln87_1_fu_358_p2 = (indvar_flatten_fu_116 + 14'd1);

assign add_ln87_fu_327_p2 = (select_ln85_fu_267_p3 + 7'd1);

assign add_ln89_fu_543_p2 = (ow_mid2_reg_714 + 7'd1);

assign add_ln91_10_fu_443_p2 = (add_ln91_9_fu_438_p2 + zext_ln85_1_reg_697);

assign add_ln91_1_fu_401_p2 = (zext_ln91_1_fu_397_p1 + ofmap);

assign add_ln91_2_fu_406_p2 = (add_ln91_1_fu_401_p2 + zext_ln91_fu_387_p1);

assign add_ln91_2_mid2_fu_448_p3 = ((select_ln85_3_reg_702[0:0] == 1'b1) ? add_ln91_10_fu_443_p2 : select_ln85_2_fu_420_p3);

assign add_ln91_3_fu_493_p2 = (add_ln91_reg_724 + zext_ln89_fu_474_p1);

assign add_ln91_4_fu_498_p2 = (zext_ln91_3_fu_489_p1 + 9'd64);

assign add_ln91_5_fu_508_p2 = (zext_ln91_4_fu_504_p1 + add_ln91_3_fu_493_p2);

assign add_ln91_6_fu_514_p2 = (add_ln91_reg_724 + zext_ln91_2_fu_485_p1);

assign add_ln91_7_fu_519_p2 = (add_ln91_6_fu_514_p2 + zext_ln89_fu_474_p1);

assign add_ln91_8_fu_415_p2 = (zext_ln91_5_fu_412_p1 + ofmap);

assign add_ln91_9_fu_438_p2 = (zext_ln91_6_fu_434_p1 + ofmap);

assign add_ln91_fu_353_p2 = (zext_ln85_1_fu_297_p1 + conv_scratch);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0_01001_grp8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp5 = ((m_axi_gmem2_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp8 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg) & (m_axi_gmem0_0_WREADY == 1'b0));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg) & (m_axi_gmem0_0_WREADY == 1'b0)) | ((m_axi_gmem2_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp5 = ((m_axi_gmem2_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp8 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg) & (m_axi_gmem0_0_WREADY == 1'b0));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state22_pp0_stage1_iter5_grp9) & (1'b0 == ap_block_pp0_stage1_subdone_grp9_done_reg)) | ((m_axi_gmem2_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg)) | ((m_axi_gmem2_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp3 = ((m_axi_gmem2_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp6 = ((m_axi_gmem2_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp9 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state22_pp0_stage1_iter5_grp9) & (1'b0 == ap_block_pp0_stage1_subdone_grp9_done_reg));
end

assign ap_block_pp0_stage1_grp3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp9 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state22_pp0_stage1_iter5_grp9) & (1'b0 == ap_block_pp0_stage1_subdone_grp9_done_reg)) | ((m_axi_gmem2_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg)) | ((m_axi_gmem2_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp3 = ((m_axi_gmem2_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp6 = ((m_axi_gmem2_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp9 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state22_pp0_stage1_iter5_grp9) & (1'b0 == ap_block_pp0_stage1_subdone_grp9_done_reg));
end

assign ap_block_pp0_stage2_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001_grp7 = ((m_axi_gmem2_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage2_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((m_axi_gmem2_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage2_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = (((m_axi_gmem2_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (((1'b1 == ap_block_state4_io_grp2) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg)) | ((1'b1 == ap_block_state4_io_grp1) & (1'b0 == ap_block_pp0_stage3_subdone_grp1_done_reg)))));
end

assign ap_block_pp0_stage3_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001_grp1 = ((1'b1 == ap_block_state4_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage3_11001_grp2 = ((1'b1 == ap_block_state4_io_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage3_11001_grp4 = ((m_axi_gmem2_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg));
end

assign ap_block_pp0_stage3_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_grp2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_grp4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = (((m_axi_gmem2_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (((1'b1 == ap_block_state4_io_grp2) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg)) | ((1'b1 == ap_block_state4_io_grp1) & (1'b0 == ap_block_pp0_stage3_subdone_grp1_done_reg)))));
end

assign ap_block_pp0_stage3_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone_grp1 = ((1'b1 == ap_block_state4_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone_grp2 = ((1'b1 == ap_block_state4_io_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone_grp4 = ((m_axi_gmem2_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg));
end

always @ (*) begin
    ap_block_state22_pp0_stage1_iter5_grp9 = ((icmp_ln89_2_reg_753_pp0_iter4_reg == 1'd1) & (m_axi_gmem0_0_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state4_io_grp1 = ((ap_predicate_op113_writereq_state4 == 1'b1) & (m_axi_gmem0_0_AWREADY == 1'b0));
end

always @ (*) begin
    ap_block_state4_io_grp2 = ((m_axi_gmem2_0_ARREADY == 1'b0) & (icmp_ln85_reg_678 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

always @ (*) begin
    ap_predicate_op113_writereq_state4 = ((first_iter_0_reg_720 == 1'd1) & (icmp_ln85_reg_678 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign empty_67_fu_333_p2 = (select_ln85_3_fu_311_p3 | icmp_ln87_fu_262_p2);

assign first_iter_0_fu_347_p2 = ((ow_mid2_fu_339_p3 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_fu_248_p2 = ((indvar_flatten25_fu_124 == mul_ln82_1) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_262_p2 = ((indvar_flatten_fu_116 == mul_ln82) ? 1'b1 : 1'b0);

assign icmp_ln89_1_fu_306_p2 = ((ow_fu_108 == lshr_ln1) ? 1'b1 : 1'b0);

assign icmp_ln89_2_fu_548_p2 = ((add_ln89_fu_543_p2 == lshr_ln1) ? 1'b1 : 1'b0);

assign icmp_ln89_fu_301_p2 = ((lshr_ln1 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln96_fu_563_p2 = (($signed(reg_195) > $signed(p01_reg_757)) ? 1'b1 : 1'b0);

assign icmp_ln97_fu_575_p2 = (($signed(p10_reg_763) > $signed(reg_195)) ? 1'b1 : 1'b0);

assign icmp_ln98_fu_587_p2 = (($signed(m0_reg_769) > $signed(m1_fu_580_p3)) ? 1'b1 : 1'b0);

assign m0_fu_568_p3 = ((icmp_ln96_fu_563_p2[0:0] == 1'b1) ? reg_195 : p01_reg_757);

assign m1_fu_580_p3 = ((icmp_ln97_fu_575_p2[0:0] == 1'b1) ? p10_reg_763 : reg_195);

assign m_axi_gmem0_0_ARADDR = 64'd0;

assign m_axi_gmem0_0_ARBURST = 2'd0;

assign m_axi_gmem0_0_ARCACHE = 4'd0;

assign m_axi_gmem0_0_ARID = 1'd0;

assign m_axi_gmem0_0_ARLEN = 32'd0;

assign m_axi_gmem0_0_ARLOCK = 2'd0;

assign m_axi_gmem0_0_ARPROT = 3'd0;

assign m_axi_gmem0_0_ARQOS = 4'd0;

assign m_axi_gmem0_0_ARREGION = 4'd0;

assign m_axi_gmem0_0_ARSIZE = 3'd0;

assign m_axi_gmem0_0_ARUSER = 1'd0;

assign m_axi_gmem0_0_ARVALID = 1'b0;

assign m_axi_gmem0_0_AWADDR = gmem0_addr_reg_730;

assign m_axi_gmem0_0_AWBURST = 2'd0;

assign m_axi_gmem0_0_AWCACHE = 4'd0;

assign m_axi_gmem0_0_AWID = 1'd0;

assign m_axi_gmem0_0_AWLEN = zext_ln85_cast_reg_663;

assign m_axi_gmem0_0_AWLOCK = 2'd0;

assign m_axi_gmem0_0_AWPROT = 3'd0;

assign m_axi_gmem0_0_AWQOS = 4'd0;

assign m_axi_gmem0_0_AWREGION = 4'd0;

assign m_axi_gmem0_0_AWSIZE = 3'd0;

assign m_axi_gmem0_0_AWUSER = 1'd0;

assign m_axi_gmem0_0_RREADY = 1'b0;

assign m_axi_gmem0_0_WDATA = select_ln98_reg_775;

assign m_axi_gmem0_0_WID = 1'd0;

assign m_axi_gmem0_0_WLAST = 1'b0;

assign m_axi_gmem0_0_WSTRB = 1'd1;

assign m_axi_gmem0_0_WUSER = 1'd0;

assign m_axi_gmem2_0_ARBURST = 2'd0;

assign m_axi_gmem2_0_ARCACHE = 4'd0;

assign m_axi_gmem2_0_ARID = 1'd0;

assign m_axi_gmem2_0_ARLEN = 64'd2;

assign m_axi_gmem2_0_ARLOCK = 2'd0;

assign m_axi_gmem2_0_ARPROT = 3'd0;

assign m_axi_gmem2_0_ARQOS = 4'd0;

assign m_axi_gmem2_0_ARREGION = 4'd0;

assign m_axi_gmem2_0_ARSIZE = 3'd0;

assign m_axi_gmem2_0_ARUSER = 1'd0;

assign m_axi_gmem2_0_AWADDR = 64'd0;

assign m_axi_gmem2_0_AWBURST = 2'd0;

assign m_axi_gmem2_0_AWCACHE = 4'd0;

assign m_axi_gmem2_0_AWID = 1'd0;

assign m_axi_gmem2_0_AWLEN = 32'd0;

assign m_axi_gmem2_0_AWLOCK = 2'd0;

assign m_axi_gmem2_0_AWPROT = 3'd0;

assign m_axi_gmem2_0_AWQOS = 4'd0;

assign m_axi_gmem2_0_AWREGION = 4'd0;

assign m_axi_gmem2_0_AWSIZE = 3'd0;

assign m_axi_gmem2_0_AWUSER = 1'd0;

assign m_axi_gmem2_0_AWVALID = 1'b0;

assign m_axi_gmem2_0_BREADY = 1'b0;

assign m_axi_gmem2_0_WDATA = 8'd0;

assign m_axi_gmem2_0_WID = 1'd0;

assign m_axi_gmem2_0_WLAST = 1'b0;

assign m_axi_gmem2_0_WSTRB = 1'd0;

assign m_axi_gmem2_0_WUSER = 1'd0;

assign m_axi_gmem2_0_WVALID = 1'b0;

assign ow_mid2_fu_339_p3 = ((empty_67_fu_333_p2[0:0] == 1'b1) ? 7'd0 : ow_fu_108);

assign select_ln85_1_fu_289_p3 = ((icmp_ln87_fu_262_p2[0:0] == 1'b1) ? shl_ln91_mid1_fu_281_p3 : shl_ln_fu_240_p3);

assign select_ln85_2_fu_420_p3 = ((icmp_ln87_reg_682[0:0] == 1'b1) ? add_ln91_8_fu_415_p2 : add_ln91_2_fu_406_p2);

assign select_ln85_3_fu_311_p3 = ((icmp_ln87_fu_262_p2[0:0] == 1'b1) ? icmp_ln89_fu_301_p2 : icmp_ln89_1_fu_306_p2);

assign select_ln85_4_fu_319_p3 = ((icmp_ln87_fu_262_p2[0:0] == 1'b1) ? add_ln85_1_fu_275_p2 : oc_fu_120);

assign select_ln85_fu_267_p3 = ((icmp_ln87_fu_262_p2[0:0] == 1'b1) ? 7'd0 : oh_fu_112);

assign select_ln87_1_fu_364_p3 = ((icmp_ln87_fu_262_p2[0:0] == 1'b1) ? 14'd1 : add_ln87_1_fu_358_p2);

assign select_ln87_fu_455_p3 = ((select_ln85_3_reg_702[0:0] == 1'b1) ? add_ln87_reg_708 : select_ln85_reg_687);

assign select_ln98_fu_592_p3 = ((icmp_ln98_fu_587_p2[0:0] == 1'b1) ? m0_reg_769 : m1_fu_580_p3);

assign shl_ln91_1_fu_466_p3 = {{select_ln87_fu_455_p3}, {7'd0}};

assign shl_ln91_2_fu_478_p3 = {{ow_mid2_reg_714}, {1'd0}};

assign shl_ln91_3_fu_390_p3 = {{oh_1_reg_668}, {6'd0}};

assign shl_ln91_3_mid1_fu_427_p3 = {{add_ln87_reg_708}, {6'd0}};

assign shl_ln91_mid1_fu_281_p3 = {{add_ln85_1_fu_275_p2}, {12'd0}};

assign shl_ln_fu_240_p3 = {{oc_fu_120}, {12'd0}};

assign zext_ln85_1_fu_297_p1 = select_ln85_1_fu_289_p3;

assign zext_ln85_cast_fu_199_p1 = zext_ln85;

assign zext_ln89_fu_474_p1 = shl_ln91_1_fu_466_p3;

assign zext_ln91_1_fu_397_p1 = shl_ln91_3_fu_390_p3;

assign zext_ln91_2_fu_485_p1 = shl_ln91_2_fu_478_p3;

assign zext_ln91_3_fu_489_p1 = shl_ln91_2_fu_478_p3;

assign zext_ln91_4_fu_504_p1 = add_ln91_4_fu_498_p2;

assign zext_ln91_5_fu_412_p1 = shl_ln91_mid1_reg_692;

assign zext_ln91_6_fu_434_p1 = shl_ln91_3_mid1_fu_427_p3;

assign zext_ln91_fu_387_p1 = shl_ln_reg_673;

always @ (posedge ap_clk) begin
    zext_ln85_cast_reg_663[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    shl_ln_reg_673[11:0] <= 12'b000000000000;
    shl_ln91_mid1_reg_692[11:0] <= 12'b000000000000;
    zext_ln85_1_reg_697[11:0] <= 12'b000000000000;
    zext_ln85_1_reg_697[63:20] <= 44'b00000000000000000000000000000000000000000000;
end

endmodule //dpu_conv_top_dpu_conv_top_Pipeline_POOL_OC_POOL_H_POOL_W
